/* The following code was generated by JFlex 1.6.1 */

package com.company;
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>battlesim.jflex</tt>
 */
class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\75\1\76\1\1\22\0\1\3\1\0\1\72"+
    "\2\0\1\65\1\0\1\74\1\55\1\56\1\5\1\63\1\61\1\64"+
    "\1\11\1\4\1\7\11\10\2\0\1\71\1\62\1\70\2\0\1\66"+
    "\1\13\1\50\1\26\1\34\1\27\1\53\1\12\1\21\2\12\1\44"+
    "\1\12\1\46\1\67\1\37\1\12\1\43\1\42\1\51\1\47\1\52"+
    "\1\23\3\12\1\57\1\6\1\60\1\0\1\12\1\0\1\17\1\73"+
    "\1\31\1\35\1\16\1\22\1\36\1\24\1\25\2\12\1\15\1\40"+
    "\1\20\1\14\1\54\1\12\1\30\1\41\1\33\1\32\1\12\1\45"+
    "\3\12\12\0\1\75\u1fa2\0\1\75\1\75\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\2\6\1\7"+
    "\25\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\2\10\1\22\1\23\1\24\1\25\2\26"+
    "\1\1\1\27\1\3\1\0\1\30\1\31\2\0\1\32"+
    "\3\10\1\33\1\34\1\10\1\35\2\10\1\36\1\37"+
    "\22\10\1\40\5\10\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\10\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\1\61\1\62\1\3\2\0"+
    "\11\10\1\63\3\10\1\64\12\10\1\65\7\10\1\66"+
    "\1\0\15\10\1\67\1\70\4\10\1\71\3\10\1\72"+
    "\1\73\1\10\1\74\1\10\1\75\1\76\3\10\1\77"+
    "\3\10\1\100\1\101\5\10\1\102\10\10\1\103\2\10"+
    "\1\104\4\10\1\105\11\10\1\106\1\107\1\110\1\10"+
    "\1\111\1\112\1\113\1\10\1\114\1\115\1\116\1\10"+
    "\1\117\1\120\1\10\1\121\1\122\1\123\1\10\1\124"+
    "\2\10\1\125\4\10\1\126\1\10\1\127\1\10\1\130";

  private static int [] zzUnpackAction() {
    int [] result = new int[252];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\77\0\176\0\275\0\176\0\176\0\374\0\u013b"+
    "\0\u017a\0\u01b9\0\u01f8\0\u0237\0\u0276\0\u02b5\0\u02f4\0\u0333"+
    "\0\u0372\0\u03b1\0\u03f0\0\u042f\0\u046e\0\u04ad\0\u04ec\0\u052b"+
    "\0\u056a\0\u05a9\0\u05e8\0\u0627\0\u0666\0\u06a5\0\u06e4\0\u0723"+
    "\0\176\0\176\0\176\0\176\0\176\0\u0762\0\u07a1\0\u07e0"+
    "\0\u081f\0\u085e\0\u089d\0\u08dc\0\u091b\0\176\0\u095a\0\u0999"+
    "\0\176\0\u09d8\0\176\0\u0a17\0\u0a56\0\176\0\176\0\u017a"+
    "\0\u01f8\0\u01f8\0\u0a95\0\u0ad4\0\u0b13\0\u0237\0\u0237\0\u0b52"+
    "\0\u0237\0\u0b91\0\u0bd0\0\u0237\0\u0c0f\0\u0c4e\0\u0c8d\0\u0ccc"+
    "\0\u0d0b\0\u0d4a\0\u0d89\0\u0dc8\0\u0e07\0\u0e46\0\u0e85\0\u0ec4"+
    "\0\u0f03\0\u0f42\0\u0f81\0\u0fc0\0\u0fff\0\u103e\0\u107d\0\u0237"+
    "\0\u10bc\0\u10fb\0\u113a\0\u1179\0\u11b8\0\176\0\176\0\176"+
    "\0\176\0\176\0\176\0\u11f7\0\u0237\0\176\0\176\0\176"+
    "\0\176\0\176\0\176\0\176\0\176\0\176\0\176\0\176"+
    "\0\u1236\0\u1275\0\u12b4\0\u12f3\0\u1332\0\u1371\0\u13b0\0\u13ef"+
    "\0\u142e\0\u146d\0\u14ac\0\u14eb\0\u152a\0\u1569\0\u15a8\0\u15e7"+
    "\0\u0237\0\u1626\0\u1665\0\u16a4\0\u16e3\0\u1722\0\u1761\0\u17a0"+
    "\0\u17df\0\u181e\0\u185d\0\u0237\0\u189c\0\u18db\0\u191a\0\u1959"+
    "\0\u1998\0\u19d7\0\u1a16\0\u0237\0\u1a55\0\u1a94\0\u1ad3\0\u1b12"+
    "\0\u1b51\0\u1b90\0\u1bcf\0\u1c0e\0\u1c4d\0\u1c8c\0\u1ccb\0\u1d0a"+
    "\0\u1d49\0\u1d88\0\u0237\0\u0237\0\u1dc7\0\u1e06\0\u1e45\0\u1e84"+
    "\0\u0237\0\u1ec3\0\u1f02\0\u1f41\0\u0237\0\u0237\0\u1f80\0\u0237"+
    "\0\u1fbf\0\u0237\0\u0237\0\u1ffe\0\u203d\0\u207c\0\u0237\0\u20bb"+
    "\0\u20fa\0\u2139\0\u0237\0\u0237\0\u2178\0\u21b7\0\u21f6\0\u2235"+
    "\0\u2274\0\u0237\0\u22b3\0\u22f2\0\u2331\0\u2370\0\u23af\0\u23ee"+
    "\0\u242d\0\u246c\0\u0237\0\u24ab\0\u24ea\0\u0237\0\u2529\0\u2568"+
    "\0\u25a7\0\u25e6\0\u0237\0\u2625\0\u2664\0\u26a3\0\u26e2\0\u2721"+
    "\0\u2760\0\u279f\0\u27de\0\u281d\0\u0237\0\u0237\0\u0237\0\u285c"+
    "\0\u0237\0\u0237\0\u0237\0\u289b\0\u0237\0\u0237\0\u0237\0\u28da"+
    "\0\u0237\0\u0237\0\u2919\0\u0237\0\u0237\0\u0237\0\u2958\0\u0237"+
    "\0\u2997\0\u29d6\0\u0237\0\u2a15\0\u2a54\0\u2a93\0\u2ad2\0\u0237"+
    "\0\u2b11\0\u0237\0\u2b50\0\u0237";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[252];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\3\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\2\14\1\17\1\14"+
    "\1\20\1\21\1\22\1\14\1\23\1\24\1\25\3\14"+
    "\1\26\1\27\2\14\1\30\2\14\1\31\1\32\1\33"+
    "\1\14\1\34\1\14\1\35\1\36\1\37\1\40\1\14"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\14\2\3"+
    "\1\6\1\57\1\60\1\61\3\57\1\62\63\57\1\63"+
    "\4\57\101\0\1\5\100\0\1\64\1\65\54\0\1\66"+
    "\76\0\1\67\23\0\2\70\1\71\74\0\2\12\1\71"+
    "\74\0\2\72\75\0\2\14\1\0\43\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\2\14\1\73\1\14"+
    "\1\74\1\75\35\14\11\0\2\14\3\0\1\14\12\0"+
    "\2\14\1\0\10\14\1\76\32\14\11\0\2\14\3\0"+
    "\1\14\12\0\2\14\1\0\27\14\1\77\13\14\11\0"+
    "\2\14\3\0\1\14\12\0\2\14\1\0\6\14\1\100"+
    "\1\14\1\101\32\14\11\0\2\14\3\0\1\14\12\0"+
    "\2\14\1\0\5\14\1\102\35\14\11\0\2\14\3\0"+
    "\1\14\12\0\2\14\1\0\12\14\1\103\30\14\11\0"+
    "\2\14\3\0\1\14\12\0\2\14\1\0\6\14\1\104"+
    "\34\14\11\0\2\14\3\0\1\14\12\0\2\14\1\0"+
    "\2\14\1\105\1\14\1\106\36\14\11\0\2\14\3\0"+
    "\1\14\12\0\2\14\1\0\2\14\1\107\15\14\1\110"+
    "\22\14\11\0\2\14\3\0\1\14\12\0\2\14\1\0"+
    "\16\14\1\111\24\14\11\0\2\14\3\0\1\14\12\0"+
    "\2\14\1\0\3\14\1\112\2\14\1\113\34\14\11\0"+
    "\2\14\3\0\1\14\12\0\2\14\1\0\3\14\1\114"+
    "\12\14\1\115\24\14\11\0\2\14\3\0\1\14\12\0"+
    "\2\14\1\0\2\14\1\116\10\14\1\117\5\14\1\120"+
    "\11\14\1\121\7\14\11\0\2\14\3\0\1\14\12\0"+
    "\2\14\1\0\4\14\1\122\36\14\11\0\2\14\3\0"+
    "\1\14\12\0\2\14\1\0\13\14\1\123\27\14\11\0"+
    "\2\14\3\0\1\14\12\0\2\14\1\0\35\14\1\124"+
    "\5\14\11\0\1\14\1\125\3\0\1\14\12\0\2\14"+
    "\1\0\2\14\1\126\2\14\1\127\35\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\2\14\1\130\1\14"+
    "\1\131\5\14\1\132\30\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\2\14\1\133\1\14\1\134\36\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\16\14"+
    "\1\135\24\14\11\0\2\14\3\0\1\14\65\0\1\136"+
    "\76\0\1\137\1\140\75\0\1\141\1\0\1\142\74\0"+
    "\1\143\23\0\2\14\1\0\34\14\1\144\6\14\11\0"+
    "\2\14\3\0\1\14\12\0\2\14\1\0\31\14\1\145"+
    "\11\14\11\0\2\14\3\0\1\14\65\0\1\146\76\0"+
    "\1\147\14\0\1\57\2\0\3\57\1\0\63\57\1\0"+
    "\4\57\2\0\1\61\74\0\1\150\2\0\3\150\1\151"+
    "\11\150\1\152\1\150\1\153\5\150\1\154\2\150\1\155"+
    "\36\150\1\156\1\157\1\160\2\0\1\64\1\161\1\6"+
    "\74\64\5\162\1\163\71\162\7\0\2\14\1\0\2\14"+
    "\1\164\40\14\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\24\14\1\165\16\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\16\14\1\166\24\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\21\14\1\167\21\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\3\14"+
    "\1\170\37\14\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\13\14\1\171\27\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\33\14\1\172\7\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\10\14\1\173\6\14"+
    "\1\174\23\14\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\16\14\1\175\24\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\6\14\1\176\34\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\20\14\1\177\22\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\27\14"+
    "\1\200\13\14\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\23\14\1\201\17\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\5\14\1\202\35\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\2\14\1\203\40\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\3\14"+
    "\1\204\37\14\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\26\14\1\205\14\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\4\14\1\206\11\14\1\207\24\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\13\14"+
    "\1\210\27\14\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\21\14\1\211\21\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\27\14\1\212\13\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\32\14\1\213\10\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\37\14"+
    "\1\214\3\14\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\2\14\1\215\40\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\27\14\1\216\13\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\16\14\1\217\24\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\4\14"+
    "\1\220\36\14\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\13\14\1\221\27\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\17\14\1\222\23\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\2\14\1\223\40\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\14\14"+
    "\1\224\26\14\11\0\2\14\3\0\1\14\5\0\1\6"+
    "\74\0\5\162\1\225\71\162\4\0\1\6\1\163\100\0"+
    "\2\14\1\0\3\14\1\226\37\14\11\0\2\14\3\0"+
    "\1\14\12\0\2\14\1\0\13\14\1\227\27\14\11\0"+
    "\2\14\3\0\1\14\12\0\2\14\1\0\16\14\1\230"+
    "\24\14\11\0\2\14\3\0\1\14\12\0\2\14\1\0"+
    "\4\14\1\231\36\14\11\0\2\14\3\0\1\14\12\0"+
    "\2\14\1\0\27\14\1\232\13\14\11\0\2\14\3\0"+
    "\1\14\12\0\2\14\1\0\3\14\1\233\37\14\11\0"+
    "\2\14\3\0\1\14\12\0\2\14\1\0\6\14\1\234"+
    "\34\14\11\0\2\14\3\0\1\14\12\0\2\14\1\0"+
    "\5\14\1\235\35\14\11\0\2\14\3\0\1\14\12\0"+
    "\2\14\1\0\3\14\1\236\7\14\1\237\27\14\11\0"+
    "\2\14\3\0\1\14\12\0\2\14\1\0\4\14\1\240"+
    "\12\14\1\241\23\14\11\0\2\14\3\0\1\14\12\0"+
    "\2\14\1\0\17\14\1\242\23\14\11\0\2\14\3\0"+
    "\1\14\12\0\2\14\1\0\4\14\1\243\36\14\11\0"+
    "\2\14\3\0\1\14\12\0\2\14\1\0\4\14\1\244"+
    "\36\14\11\0\2\14\3\0\1\14\12\0\2\14\1\0"+
    "\21\14\1\245\21\14\11\0\2\14\3\0\1\14\12\0"+
    "\2\14\1\0\24\14\1\246\16\14\11\0\2\14\3\0"+
    "\1\14\12\0\2\14\1\0\23\14\1\247\17\14\11\0"+
    "\2\14\3\0\1\14\12\0\2\14\1\0\20\14\1\250"+
    "\22\14\11\0\2\14\3\0\1\14\12\0\2\14\1\0"+
    "\42\14\1\251\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\13\14\1\252\27\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\21\14\1\253\21\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\20\14\1\254\22\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\21\14"+
    "\1\255\21\14\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\32\14\1\256\10\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\16\14\1\257\24\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\4\14\1\260\36\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\16\14"+
    "\1\261\24\14\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\6\14\1\262\34\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\23\14\1\263\17\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\21\14\1\264\21\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\20\14"+
    "\1\265\22\14\11\0\2\14\3\0\1\14\3\0\4\162"+
    "\1\6\1\225\71\162\7\0\2\14\1\0\4\14\1\266"+
    "\36\14\11\0\2\14\3\0\1\14\12\0\2\14\1\0"+
    "\6\14\1\267\34\14\11\0\2\14\3\0\1\14\12\0"+
    "\2\14\1\0\13\14\1\270\27\14\11\0\2\14\3\0"+
    "\1\14\12\0\2\14\1\0\16\14\1\271\5\14\1\272"+
    "\16\14\11\0\2\14\3\0\1\14\12\0\2\14\1\0"+
    "\4\14\1\273\36\14\11\0\2\14\3\0\1\14\12\0"+
    "\2\14\1\0\4\14\1\274\36\14\11\0\2\14\3\0"+
    "\1\14\12\0\2\14\1\0\37\14\1\275\3\14\11\0"+
    "\2\14\3\0\1\14\12\0\2\14\1\0\20\14\1\276"+
    "\22\14\11\0\2\14\3\0\1\14\12\0\2\14\1\0"+
    "\5\14\1\277\35\14\11\0\2\14\3\0\1\14\12\0"+
    "\2\14\1\0\26\14\1\300\14\14\11\0\2\14\3\0"+
    "\1\14\12\0\2\14\1\0\5\14\1\301\35\14\11\0"+
    "\2\14\3\0\1\14\12\0\2\14\1\0\4\14\1\302"+
    "\36\14\11\0\2\14\3\0\1\14\12\0\2\14\1\0"+
    "\21\14\1\303\21\14\11\0\2\14\3\0\1\14\12\0"+
    "\2\14\1\0\2\14\1\304\40\14\11\0\2\14\3\0"+
    "\1\14\12\0\2\14\1\0\16\14\1\305\24\14\11\0"+
    "\2\14\3\0\1\14\12\0\2\14\1\0\13\14\1\306"+
    "\27\14\11\0\2\14\3\0\1\14\12\0\2\14\1\0"+
    "\3\14\1\307\37\14\11\0\2\14\3\0\1\14\12\0"+
    "\2\14\1\0\6\14\1\310\34\14\11\0\2\14\3\0"+
    "\1\14\12\0\2\14\1\0\17\14\1\311\23\14\11\0"+
    "\2\14\3\0\1\14\12\0\2\14\1\0\16\14\1\312"+
    "\24\14\11\0\2\14\3\0\1\14\12\0\2\14\1\0"+
    "\23\14\1\313\17\14\11\0\2\14\3\0\1\14\12\0"+
    "\2\14\1\0\5\14\1\314\35\14\11\0\2\14\3\0"+
    "\1\14\12\0\2\14\1\0\2\14\1\315\40\14\11\0"+
    "\2\14\3\0\1\14\12\0\2\14\1\0\42\14\1\316"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\5\14"+
    "\1\317\35\14\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\4\14\1\320\36\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\16\14\1\321\24\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\4\14\1\322\36\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\2\14"+
    "\1\323\40\14\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\3\14\1\324\37\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\16\14\1\325\24\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\5\14\1\326\35\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\17\14"+
    "\1\327\23\14\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\13\14\1\330\27\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\2\14\1\331\40\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\5\14\1\332\35\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\4\14"+
    "\1\333\36\14\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\5\14\1\334\35\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\24\14\1\335\16\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\12\14\1\336\30\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\6\14"+
    "\1\337\34\14\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\13\14\1\340\27\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\16\14\1\341\24\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\6\14\1\342\34\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\16\14"+
    "\1\343\24\14\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\20\14\1\344\22\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\16\14\1\345\24\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\21\14\1\346\21\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\4\14"+
    "\1\347\1\350\35\14\11\0\2\14\3\0\1\14\12\0"+
    "\2\14\1\0\3\14\1\351\37\14\11\0\2\14\3\0"+
    "\1\14\12\0\2\14\1\0\12\14\1\352\30\14\11\0"+
    "\2\14\3\0\1\14\12\0\2\14\1\0\2\14\1\353"+
    "\40\14\11\0\2\14\3\0\1\14\12\0\2\14\1\0"+
    "\6\14\1\354\34\14\11\0\2\14\3\0\1\14\12\0"+
    "\2\14\1\0\26\14\1\355\14\14\11\0\2\14\3\0"+
    "\1\14\12\0\2\14\1\0\16\14\1\356\24\14\11\0"+
    "\2\14\3\0\1\14\12\0\2\14\1\0\21\14\1\357"+
    "\21\14\11\0\2\14\3\0\1\14\12\0\2\14\1\0"+
    "\6\14\1\360\34\14\11\0\2\14\3\0\1\14\12\0"+
    "\2\14\1\0\42\14\1\361\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\21\14\1\362\21\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\6\14\1\363\34\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\13\14"+
    "\1\364\27\14\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\21\14\1\365\21\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\13\14\1\366\27\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\2\14\1\367\40\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\27\14"+
    "\1\370\13\14\11\0\2\14\3\0\1\14\12\0\2\14"+
    "\1\0\2\14\1\371\40\14\11\0\2\14\3\0\1\14"+
    "\12\0\2\14\1\0\6\14\1\372\34\14\11\0\2\14"+
    "\3\0\1\14\12\0\2\14\1\0\6\14\1\373\34\14"+
    "\11\0\2\14\3\0\1\14\12\0\2\14\1\0\27\14"+
    "\1\374\13\14\11\0\2\14\3\0\1\14\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11151];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\2\11\32\1\5\11\10\1\1\11"+
    "\2\1\1\11\1\1\1\11\1\1\1\0\2\11\2\0"+
    "\44\1\6\11\2\1\13\11\1\1\2\0\41\1\1\0"+
    "\147\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[252];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
      StringBuffer string = new StringBuffer();

      private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
      }
      private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
      }

      /* This is required, as ZZAtEOF is private */
      public boolean getZZAtEOF() {
        return zzAtEOF;
      }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 206) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(Sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new RuntimeException("Illegal character \""+yytext()+"\" at line "+yyline+", column "+yycolumn);
            }
          case 89: break;
          case 2: 
            { return symbol(Sym.EOL);
            }
          case 90: break;
          case 3: 
            { /* nothing happens here, maybe */
            }
          case 91: break;
          case 4: 
            { return symbol(Sym.DIV);
            }
          case 92: break;
          case 5: 
            { return symbol(Sym.MULT);
            }
          case 93: break;
          case 6: 
            { return symbol(Sym.INTEGER_LITERAL, new Integer(yytext()));
            }
          case 94: break;
          case 7: 
            { return symbol(Sym.DOT);
            }
          case 95: break;
          case 8: 
            { return symbol(Sym.IDENTIFIER, yytext());
            }
          case 96: break;
          case 9: 
            { return symbol(Sym.LPAREN);
            }
          case 97: break;
          case 10: 
            { return symbol(Sym.RPAREN);
            }
          case 98: break;
          case 11: 
            { return symbol(Sym.LBRACE);
            }
          case 99: break;
          case 12: 
            { return symbol(Sym.RBRACE);
            }
          case 100: break;
          case 13: 
            { return symbol(Sym.COMMA);
            }
          case 101: break;
          case 14: 
            { return symbol(Sym.EQ);
            }
          case 102: break;
          case 15: 
            { return symbol(Sym.PLUS);
            }
          case 103: break;
          case 16: 
            { return symbol(Sym.MINUS);
            }
          case 104: break;
          case 17: 
            { return symbol(Sym.MOD);
            }
          case 105: break;
          case 18: 
            { return symbol(Sym.GREATERTHAN);
            }
          case 106: break;
          case 19: 
            { return symbol(Sym.LESSTHAN);
            }
          case 107: break;
          case 20: 
            { yybegin(STRING); string.setLength(0);
            }
          case 108: break;
          case 21: 
            { string.append( yytext() );
            }
          case 109: break;
          case 22: 
            { throw new RuntimeException("Unterminated string at end of line");
            }
          case 110: break;
          case 23: 
            { yybegin(YYINITIAL); return symbol(Sym.STRING_LITERAL, string.toString());
            }
          case 111: break;
          case 24: 
            { return symbol(Sym.DIVEQ);
            }
          case 112: break;
          case 25: 
            { return symbol(Sym.MULTEQ);
            }
          case 113: break;
          case 26: 
            { return symbol(Sym.DECIMAL_LITERAL, new Double(yytext()));
            }
          case 114: break;
          case 27: 
            { return symbol(Sym.OF);
            }
          case 115: break;
          case 28: 
            { return symbol(Sym.AS);
            }
          case 116: break;
          case 29: 
            { return symbol(Sym.IF);
            }
          case 117: break;
          case 30: 
            { return symbol(Sym.IN);
            }
          case 118: break;
          case 31: 
            { return symbol(Sym.DO);
            }
          case 119: break;
          case 32: 
            { return symbol(Sym.TO);
            }
          case 120: break;
          case 33: 
            { return symbol(Sym.EQUALS);
            }
          case 121: break;
          case 34: 
            { return symbol(Sym.PLUSEQ);
            }
          case 122: break;
          case 35: 
            { return symbol(Sym.PLUSPLUS);
            }
          case 123: break;
          case 36: 
            { return symbol(Sym.MINUSEQ);
            }
          case 124: break;
          case 37: 
            { return symbol(Sym.MINUSMINUS);
            }
          case 125: break;
          case 38: 
            { return symbol(Sym.MODEQ);
            }
          case 126: break;
          case 39: 
            { return symbol(Sym.OR);
            }
          case 127: break;
          case 40: 
            { return symbol(Sym.GREATERTHANEQUALS);
            }
          case 128: break;
          case 41: 
            { return symbol(Sym.LESSTHANEQUALS);
            }
          case 129: break;
          case 42: 
            { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
            }
          case 130: break;
          case 43: 
            { string.append( '\\' );
            }
          case 131: break;
          case 44: 
            { string.append( '\n' );
            }
          case 132: break;
          case 45: 
            { string.append( '\f' );
            }
          case 133: break;
          case 46: 
            { string.append( '\r' );
            }
          case 134: break;
          case 47: 
            { string.append( '\t' );
            }
          case 135: break;
          case 48: 
            { string.append( '\"' );
            }
          case 136: break;
          case 49: 
            { string.append( '\b' );
            }
          case 137: break;
          case 50: 
            { string.append( '\'' );
            }
          case 138: break;
          case 51: 
            { return symbol(Sym.FOR);
            }
          case 139: break;
          case 52: 
            { return symbol(Sym.END);
            }
          case 140: break;
          case 53: 
            { return symbol(Sym.NOT);
            }
          case 141: break;
          case 54: 
            { return symbol(Sym.AND);
            }
          case 142: break;
          case 55: 
            { return symbol(Sym.BOOLEAN_LITERAL, true);
            }
          case 143: break;
          case 56: 
            { return symbol(Sym.ELSE);
            }
          case 144: break;
          case 57: 
            { return symbol(Sym.STEP);
            }
          case 145: break;
          case 58: 
            { return symbol(Sym.LIST);
            }
          case 146: break;
          case 59: 
            { return symbol(Sym.NULL_LITERAL);
            }
          case 147: break;
          case 60: 
            { return symbol(Sym.CASE);
            }
          case 148: break;
          case 61: 
            { return symbol(Sym.THEN);
            }
          case 149: break;
          case 62: 
            { return symbol(Sym.VOID);
            }
          case 150: break;
          case 63: 
            { return symbol(Sym.BEGIN);
            }
          case 151: break;
          case 64: 
            { return symbol(Sym.BOOLEAN_LITERAL, false);
            }
          case 152: break;
          case 65: 
            { return symbol(Sym.WHILE);
            }
          case 153: break;
          case 66: 
            { return symbol(Sym.FORCE);
            }
          case 154: break;
          case 67: 
            { return symbol(Sym.COORD);
            }
          case 155: break;
          case 68: 
            { return symbol(Sym.GROUP);
            }
          case 156: break;
          case 69: 
            { return symbol(Sym.DOWNTO);
            }
          case 157: break;
          case 70: 
            { return symbol(Sym.STRING);
            }
          case 158: break;
          case 71: 
            { return symbol(Sym.SWITCH);
            }
          case 159: break;
          case 72: 
            { return symbol(Sym.RETURN);
            }
          case 160: break;
          case 73: 
            { return symbol(Sym.VECTOR);
            }
          case 161: break;
          case 74: 
            { return symbol(Sym.BOOLEAN);
            }
          case 162: break;
          case 75: 
            { return symbol(Sym.BARRIER);
            }
          case 163: break;
          case 76: 
            { return symbol(Sym.INTEGER);
            }
          case 164: break;
          case 77: 
            { return symbol(Sym.DEFAULT);
            }
          case 165: break;
          case 78: 
            { return symbol(Sym.DECLARE);
            }
          case 166: break;
          case 79: 
            { return symbol(Sym.DECIMAL);
            }
          case 167: break;
          case 80: 
            { return symbol(Sym.FOREACH);
            }
          case 168: break;
          case 81: 
            { return symbol(Sym.PLATOON);
            }
          case 169: break;
          case 82: 
            { return symbol(Sym.PROGRAM);
            }
          case 170: break;
          case 83: 
            { return symbol(Sym.SOLDIER);
            }
          case 171: break;
          case 84: 
            { return symbol(Sym.TERRAIN);
            }
          case 172: break;
          case 85: 
            { return symbol(Sym.FUNCTION);
            }
          case 173: break;
          case 86: 
            { return symbol(Sym.INTERRUPTS);
            }
          case 174: break;
          case 87: 
            { return symbol(Sym.SIMULATION);
            }
          case 175: break;
          case 88: 
            { return symbol(Sym.DECLARATIONS);
            }
          case 176: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
