/* The following code was generated by JFlex 1.6.1 */

package com.company;
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>battlesim.jflex</tt>
 */
class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\75\1\76\1\1\22\0\1\3\1\0\1\72"+
    "\2\0\1\65\1\0\1\74\1\55\1\56\1\5\1\63\1\61\1\64"+
    "\1\11\1\4\1\7\11\10\2\0\1\71\1\62\1\70\2\0\1\66"+
    "\1\13\1\50\1\26\1\34\1\27\1\53\1\12\1\21\2\12\1\44"+
    "\1\12\1\46\1\67\1\37\1\12\1\43\1\42\1\51\1\47\1\52"+
    "\1\23\3\12\1\57\1\6\1\60\1\0\1\12\1\0\1\17\1\73"+
    "\1\31\1\35\1\16\1\22\1\36\1\24\1\25\2\12\1\15\1\40"+
    "\1\20\1\14\1\54\1\12\1\30\1\41\1\33\1\32\1\12\1\45"+
    "\3\12\12\0\1\75\u1fa2\0\1\75\1\75\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\2\5\1\6\25\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\2\7\1\21\1\22\1\23\1\24\2\25\1\1"+
    "\1\26\1\2\1\0\1\27\1\30\2\0\1\31\3\7"+
    "\1\32\1\33\1\7\1\34\2\7\1\35\1\36\22\7"+
    "\1\37\5\7\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\7\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\1\61\2\0\11\7\1\62"+
    "\3\7\1\63\12\7\1\64\7\7\1\65\1\0\15\7"+
    "\1\66\1\67\4\7\1\70\3\7\1\71\1\72\1\7"+
    "\1\73\1\7\1\74\1\75\3\7\1\76\2\7\1\77"+
    "\1\100\5\7\1\101\10\7\1\102\2\7\1\103\3\7"+
    "\1\104\11\7\1\105\1\106\1\107\1\7\1\110\1\111"+
    "\1\112\1\7\1\113\1\114\1\7\1\115\1\116\1\7"+
    "\1\117\1\120\1\121\1\7\1\122\2\7\1\123\4\7"+
    "\1\124\1\7\1\125\1\7\1\126";

  private static int [] zzUnpackAction() {
    int [] result = new int[247];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\77\0\176\0\275\0\176\0\374\0\u013b\0\u017a"+
    "\0\u01b9\0\u01f8\0\u0237\0\u0276\0\u02b5\0\u02f4\0\u0333\0\u0372"+
    "\0\u03b1\0\u03f0\0\u042f\0\u046e\0\u04ad\0\u04ec\0\u052b\0\u056a"+
    "\0\u05a9\0\u05e8\0\u0627\0\u0666\0\u06a5\0\u06e4\0\u0723\0\176"+
    "\0\176\0\176\0\176\0\176\0\u0762\0\u07a1\0\u07e0\0\u081f"+
    "\0\u085e\0\u089d\0\u08dc\0\u091b\0\176\0\u095a\0\u0999\0\176"+
    "\0\u09d8\0\176\0\u0a17\0\u0a56\0\176\0\176\0\u017a\0\u01f8"+
    "\0\u01f8\0\u0a95\0\u0ad4\0\u0b13\0\u0237\0\u0237\0\u0b52\0\u0237"+
    "\0\u0b91\0\u0bd0\0\u0237\0\u0c0f\0\u0c4e\0\u0c8d\0\u0ccc\0\u0d0b"+
    "\0\u0d4a\0\u0d89\0\u0dc8\0\u0e07\0\u0e46\0\u0e85\0\u0ec4\0\u0f03"+
    "\0\u0f42\0\u0f81\0\u0fc0\0\u0fff\0\u103e\0\u107d\0\u0237\0\u10bc"+
    "\0\u10fb\0\u113a\0\u1179\0\u11b8\0\176\0\176\0\176\0\176"+
    "\0\176\0\176\0\u11f7\0\u0237\0\176\0\176\0\176\0\176"+
    "\0\176\0\176\0\176\0\176\0\176\0\176\0\176\0\u1236"+
    "\0\u1275\0\u12b4\0\u12f3\0\u1332\0\u1371\0\u13b0\0\u13ef\0\u142e"+
    "\0\u146d\0\u14ac\0\u14eb\0\u152a\0\u1569\0\u15a8\0\u0237\0\u15e7"+
    "\0\u1626\0\u1665\0\u16a4\0\u16e3\0\u1722\0\u1761\0\u17a0\0\u17df"+
    "\0\u181e\0\u0237\0\u185d\0\u189c\0\u18db\0\u191a\0\u1959\0\u1998"+
    "\0\u19d7\0\u0237\0\u1a16\0\u1a55\0\u1a94\0\u1ad3\0\u1b12\0\u1b51"+
    "\0\u1b90\0\u1bcf\0\u1c0e\0\u1c4d\0\u1c8c\0\u1ccb\0\u1d0a\0\u1d49"+
    "\0\u0237\0\u0237\0\u1d88\0\u1dc7\0\u1e06\0\u1e45\0\u0237\0\u1e84"+
    "\0\u1ec3\0\u1f02\0\u0237\0\u0237\0\u1f41\0\u0237\0\u1f80\0\u0237"+
    "\0\u0237\0\u1fbf\0\u1ffe\0\u203d\0\u0237\0\u207c\0\u20bb\0\u0237"+
    "\0\u0237\0\u20fa\0\u2139\0\u2178\0\u21b7\0\u21f6\0\u0237\0\u2235"+
    "\0\u2274\0\u22b3\0\u22f2\0\u2331\0\u2370\0\u23af\0\u23ee\0\u0237"+
    "\0\u242d\0\u246c\0\u0237\0\u24ab\0\u24ea\0\u2529\0\u0237\0\u2568"+
    "\0\u25a7\0\u25e6\0\u2625\0\u2664\0\u26a3\0\u26e2\0\u2721\0\u2760"+
    "\0\u0237\0\u0237\0\u0237\0\u279f\0\u0237\0\u0237\0\u0237\0\u27de"+
    "\0\u0237\0\u0237\0\u281d\0\u0237\0\u0237\0\u285c\0\u0237\0\u0237"+
    "\0\u0237\0\u289b\0\u0237\0\u28da\0\u2919\0\u0237\0\u2958\0\u2997"+
    "\0\u29d6\0\u2a15\0\u0237\0\u2a54\0\u0237\0\u2a93\0\u0237";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[247];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\7\1\3\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\2\13\1\16\1\13\1\17"+
    "\1\20\1\21\1\13\1\22\1\23\1\24\3\13\1\25"+
    "\1\26\2\13\1\27\2\13\1\30\1\31\1\32\1\13"+
    "\1\33\1\13\1\34\1\35\1\36\1\37\1\13\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\13\2\3\1\5"+
    "\1\56\1\57\1\60\3\56\1\61\63\56\1\62\4\56"+
    "\101\0\1\5\100\0\1\63\1\64\54\0\1\65\76\0"+
    "\1\66\23\0\2\67\1\70\74\0\2\11\1\70\74\0"+
    "\2\71\75\0\2\13\1\0\43\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\2\13\1\72\1\13\1\73"+
    "\1\74\35\13\11\0\2\13\3\0\1\13\12\0\2\13"+
    "\1\0\10\13\1\75\32\13\11\0\2\13\3\0\1\13"+
    "\12\0\2\13\1\0\27\13\1\76\13\13\11\0\2\13"+
    "\3\0\1\13\12\0\2\13\1\0\6\13\1\77\1\13"+
    "\1\100\32\13\11\0\2\13\3\0\1\13\12\0\2\13"+
    "\1\0\5\13\1\101\35\13\11\0\2\13\3\0\1\13"+
    "\12\0\2\13\1\0\12\13\1\102\30\13\11\0\2\13"+
    "\3\0\1\13\12\0\2\13\1\0\6\13\1\103\34\13"+
    "\11\0\2\13\3\0\1\13\12\0\2\13\1\0\2\13"+
    "\1\104\1\13\1\105\36\13\11\0\2\13\3\0\1\13"+
    "\12\0\2\13\1\0\2\13\1\106\15\13\1\107\22\13"+
    "\11\0\2\13\3\0\1\13\12\0\2\13\1\0\16\13"+
    "\1\110\24\13\11\0\2\13\3\0\1\13\12\0\2\13"+
    "\1\0\3\13\1\111\2\13\1\112\34\13\11\0\2\13"+
    "\3\0\1\13\12\0\2\13\1\0\3\13\1\113\12\13"+
    "\1\114\24\13\11\0\2\13\3\0\1\13\12\0\2\13"+
    "\1\0\2\13\1\115\10\13\1\116\5\13\1\117\11\13"+
    "\1\120\7\13\11\0\2\13\3\0\1\13\12\0\2\13"+
    "\1\0\4\13\1\121\36\13\11\0\2\13\3\0\1\13"+
    "\12\0\2\13\1\0\13\13\1\122\27\13\11\0\2\13"+
    "\3\0\1\13\12\0\2\13\1\0\35\13\1\123\5\13"+
    "\11\0\1\13\1\124\3\0\1\13\12\0\2\13\1\0"+
    "\2\13\1\125\2\13\1\126\35\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\2\13\1\127\1\13\1\130"+
    "\5\13\1\131\30\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\2\13\1\132\1\13\1\133\36\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\16\13\1\134"+
    "\24\13\11\0\2\13\3\0\1\13\65\0\1\135\76\0"+
    "\1\136\1\137\75\0\1\140\1\0\1\141\74\0\1\142"+
    "\23\0\2\13\1\0\34\13\1\143\6\13\11\0\2\13"+
    "\3\0\1\13\12\0\2\13\1\0\31\13\1\144\11\13"+
    "\11\0\2\13\3\0\1\13\65\0\1\145\76\0\1\146"+
    "\14\0\1\56\2\0\3\56\1\0\63\56\1\0\4\56"+
    "\2\0\1\60\74\0\1\147\2\0\3\147\1\150\11\147"+
    "\1\151\1\147\1\152\5\147\1\153\2\147\1\154\36\147"+
    "\1\155\1\156\1\157\2\0\1\63\1\4\1\5\74\63"+
    "\5\160\1\161\71\160\7\0\2\13\1\0\2\13\1\162"+
    "\40\13\11\0\2\13\3\0\1\13\12\0\2\13\1\0"+
    "\24\13\1\163\16\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\16\13\1\164\24\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\21\13\1\165\21\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\3\13\1\166"+
    "\37\13\11\0\2\13\3\0\1\13\12\0\2\13\1\0"+
    "\13\13\1\167\27\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\33\13\1\170\7\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\10\13\1\171\6\13\1\172"+
    "\23\13\11\0\2\13\3\0\1\13\12\0\2\13\1\0"+
    "\16\13\1\173\24\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\6\13\1\174\34\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\20\13\1\175\22\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\27\13\1\176"+
    "\13\13\11\0\2\13\3\0\1\13\12\0\2\13\1\0"+
    "\23\13\1\177\17\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\5\13\1\200\35\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\2\13\1\201\40\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\3\13\1\202"+
    "\37\13\11\0\2\13\3\0\1\13\12\0\2\13\1\0"+
    "\26\13\1\203\14\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\4\13\1\204\11\13\1\205\24\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\13\13\1\206"+
    "\27\13\11\0\2\13\3\0\1\13\12\0\2\13\1\0"+
    "\21\13\1\207\21\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\27\13\1\210\13\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\32\13\1\211\10\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\37\13\1\212"+
    "\3\13\11\0\2\13\3\0\1\13\12\0\2\13\1\0"+
    "\2\13\1\213\40\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\27\13\1\214\13\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\16\13\1\215\24\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\4\13\1\216"+
    "\36\13\11\0\2\13\3\0\1\13\12\0\2\13\1\0"+
    "\13\13\1\217\27\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\17\13\1\220\23\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\2\13\1\221\40\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\14\13\1\222"+
    "\26\13\11\0\2\13\3\0\1\13\3\0\5\160\1\223"+
    "\71\160\4\0\1\5\1\161\100\0\2\13\1\0\3\13"+
    "\1\224\37\13\11\0\2\13\3\0\1\13\12\0\2\13"+
    "\1\0\13\13\1\225\27\13\11\0\2\13\3\0\1\13"+
    "\12\0\2\13\1\0\16\13\1\226\24\13\11\0\2\13"+
    "\3\0\1\13\12\0\2\13\1\0\4\13\1\227\36\13"+
    "\11\0\2\13\3\0\1\13\12\0\2\13\1\0\27\13"+
    "\1\230\13\13\11\0\2\13\3\0\1\13\12\0\2\13"+
    "\1\0\3\13\1\231\37\13\11\0\2\13\3\0\1\13"+
    "\12\0\2\13\1\0\6\13\1\232\34\13\11\0\2\13"+
    "\3\0\1\13\12\0\2\13\1\0\5\13\1\233\35\13"+
    "\11\0\2\13\3\0\1\13\12\0\2\13\1\0\3\13"+
    "\1\234\7\13\1\235\27\13\11\0\2\13\3\0\1\13"+
    "\12\0\2\13\1\0\4\13\1\236\12\13\1\237\23\13"+
    "\11\0\2\13\3\0\1\13\12\0\2\13\1\0\17\13"+
    "\1\240\23\13\11\0\2\13\3\0\1\13\12\0\2\13"+
    "\1\0\4\13\1\241\36\13\11\0\2\13\3\0\1\13"+
    "\12\0\2\13\1\0\4\13\1\242\36\13\11\0\2\13"+
    "\3\0\1\13\12\0\2\13\1\0\21\13\1\243\21\13"+
    "\11\0\2\13\3\0\1\13\12\0\2\13\1\0\24\13"+
    "\1\244\16\13\11\0\2\13\3\0\1\13\12\0\2\13"+
    "\1\0\23\13\1\245\17\13\11\0\2\13\3\0\1\13"+
    "\12\0\2\13\1\0\20\13\1\246\22\13\11\0\2\13"+
    "\3\0\1\13\12\0\2\13\1\0\42\13\1\247\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\13\13\1\250"+
    "\27\13\11\0\2\13\3\0\1\13\12\0\2\13\1\0"+
    "\21\13\1\251\21\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\20\13\1\252\22\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\21\13\1\253\21\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\32\13\1\254"+
    "\10\13\11\0\2\13\3\0\1\13\12\0\2\13\1\0"+
    "\16\13\1\255\24\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\4\13\1\256\36\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\16\13\1\257\24\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\6\13\1\260"+
    "\34\13\11\0\2\13\3\0\1\13\12\0\2\13\1\0"+
    "\23\13\1\261\17\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\21\13\1\262\21\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\20\13\1\263\22\13\11\0"+
    "\2\13\3\0\1\13\3\0\4\160\1\5\1\223\71\160"+
    "\7\0\2\13\1\0\4\13\1\264\36\13\11\0\2\13"+
    "\3\0\1\13\12\0\2\13\1\0\6\13\1\265\34\13"+
    "\11\0\2\13\3\0\1\13\12\0\2\13\1\0\13\13"+
    "\1\266\27\13\11\0\2\13\3\0\1\13\12\0\2\13"+
    "\1\0\16\13\1\267\24\13\11\0\2\13\3\0\1\13"+
    "\12\0\2\13\1\0\4\13\1\270\36\13\11\0\2\13"+
    "\3\0\1\13\12\0\2\13\1\0\4\13\1\271\36\13"+
    "\11\0\2\13\3\0\1\13\12\0\2\13\1\0\37\13"+
    "\1\272\3\13\11\0\2\13\3\0\1\13\12\0\2\13"+
    "\1\0\20\13\1\273\22\13\11\0\2\13\3\0\1\13"+
    "\12\0\2\13\1\0\5\13\1\274\35\13\11\0\2\13"+
    "\3\0\1\13\12\0\2\13\1\0\26\13\1\275\14\13"+
    "\11\0\2\13\3\0\1\13\12\0\2\13\1\0\5\13"+
    "\1\276\35\13\11\0\2\13\3\0\1\13\12\0\2\13"+
    "\1\0\4\13\1\277\36\13\11\0\2\13\3\0\1\13"+
    "\12\0\2\13\1\0\21\13\1\300\21\13\11\0\2\13"+
    "\3\0\1\13\12\0\2\13\1\0\2\13\1\301\40\13"+
    "\11\0\2\13\3\0\1\13\12\0\2\13\1\0\16\13"+
    "\1\302\24\13\11\0\2\13\3\0\1\13\12\0\2\13"+
    "\1\0\13\13\1\303\27\13\11\0\2\13\3\0\1\13"+
    "\12\0\2\13\1\0\3\13\1\304\37\13\11\0\2\13"+
    "\3\0\1\13\12\0\2\13\1\0\6\13\1\305\34\13"+
    "\11\0\2\13\3\0\1\13\12\0\2\13\1\0\17\13"+
    "\1\306\23\13\11\0\2\13\3\0\1\13\12\0\2\13"+
    "\1\0\16\13\1\307\24\13\11\0\2\13\3\0\1\13"+
    "\12\0\2\13\1\0\23\13\1\310\17\13\11\0\2\13"+
    "\3\0\1\13\12\0\2\13\1\0\5\13\1\311\35\13"+
    "\11\0\2\13\3\0\1\13\12\0\2\13\1\0\2\13"+
    "\1\312\40\13\11\0\2\13\3\0\1\13\12\0\2\13"+
    "\1\0\42\13\1\313\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\5\13\1\314\35\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\4\13\1\315\36\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\16\13\1\316"+
    "\24\13\11\0\2\13\3\0\1\13\12\0\2\13\1\0"+
    "\2\13\1\317\40\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\3\13\1\320\37\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\16\13\1\321\24\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\5\13\1\322"+
    "\35\13\11\0\2\13\3\0\1\13\12\0\2\13\1\0"+
    "\17\13\1\323\23\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\13\13\1\324\27\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\2\13\1\325\40\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\5\13\1\326"+
    "\35\13\11\0\2\13\3\0\1\13\12\0\2\13\1\0"+
    "\4\13\1\327\36\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\5\13\1\330\35\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\24\13\1\331\16\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\12\13\1\332"+
    "\30\13\11\0\2\13\3\0\1\13\12\0\2\13\1\0"+
    "\6\13\1\333\34\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\13\13\1\334\27\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\16\13\1\335\24\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\6\13\1\336"+
    "\34\13\11\0\2\13\3\0\1\13\12\0\2\13\1\0"+
    "\16\13\1\337\24\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\20\13\1\340\22\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\21\13\1\341\21\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\4\13\1\342"+
    "\1\343\35\13\11\0\2\13\3\0\1\13\12\0\2\13"+
    "\1\0\3\13\1\344\37\13\11\0\2\13\3\0\1\13"+
    "\12\0\2\13\1\0\12\13\1\345\30\13\11\0\2\13"+
    "\3\0\1\13\12\0\2\13\1\0\2\13\1\346\40\13"+
    "\11\0\2\13\3\0\1\13\12\0\2\13\1\0\6\13"+
    "\1\347\34\13\11\0\2\13\3\0\1\13\12\0\2\13"+
    "\1\0\26\13\1\350\14\13\11\0\2\13\3\0\1\13"+
    "\12\0\2\13\1\0\16\13\1\351\24\13\11\0\2\13"+
    "\3\0\1\13\12\0\2\13\1\0\21\13\1\352\21\13"+
    "\11\0\2\13\3\0\1\13\12\0\2\13\1\0\6\13"+
    "\1\353\34\13\11\0\2\13\3\0\1\13\12\0\2\13"+
    "\1\0\42\13\1\354\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\21\13\1\355\21\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\6\13\1\356\34\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\13\13\1\357"+
    "\27\13\11\0\2\13\3\0\1\13\12\0\2\13\1\0"+
    "\21\13\1\360\21\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\13\13\1\361\27\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\2\13\1\362\40\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\27\13\1\363"+
    "\13\13\11\0\2\13\3\0\1\13\12\0\2\13\1\0"+
    "\2\13\1\364\40\13\11\0\2\13\3\0\1\13\12\0"+
    "\2\13\1\0\6\13\1\365\34\13\11\0\2\13\3\0"+
    "\1\13\12\0\2\13\1\0\6\13\1\366\34\13\11\0"+
    "\2\13\3\0\1\13\12\0\2\13\1\0\27\13\1\367"+
    "\13\13\11\0\2\13\3\0\1\13\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10962];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\32\1\5\11\10\1\1\11"+
    "\2\1\1\11\1\1\1\11\1\1\1\0\2\11\2\0"+
    "\44\1\6\11\2\1\13\11\2\0\41\1\1\0\144\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[247];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
      StringBuffer string = new StringBuffer();

      private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
      }
      private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
      }

      /* This is required, as ZZAtEOF is private */
      public boolean getZZAtEOF() {
        return zzAtEOF;
      }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 206) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(Sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new RuntimeException("Illegal character \""+yytext()+"\" at line "+yyline+", column "+yycolumn);
            }
          case 87: break;
          case 2: 
            { /* nothing happens here, maybe */
            }
          case 88: break;
          case 3: 
            { return symbol(Sym.DIV);
            }
          case 89: break;
          case 4: 
            { return symbol(Sym.MULT);
            }
          case 90: break;
          case 5: 
            { return symbol(Sym.INTEGER_LITERAL, new Integer(yytext()));
            }
          case 91: break;
          case 6: 
            { return symbol(Sym.DOT);
            }
          case 92: break;
          case 7: 
            { return symbol(Sym.IDENTIFIER, yytext());
            }
          case 93: break;
          case 8: 
            { return symbol(Sym.LPAREN);
            }
          case 94: break;
          case 9: 
            { return symbol(Sym.RPAREN);
            }
          case 95: break;
          case 10: 
            { return symbol(Sym.LBRACE);
            }
          case 96: break;
          case 11: 
            { return symbol(Sym.RBRACE);
            }
          case 97: break;
          case 12: 
            { return symbol(Sym.COMMA);
            }
          case 98: break;
          case 13: 
            { return symbol(Sym.EQ);
            }
          case 99: break;
          case 14: 
            { return symbol(Sym.PLUS);
            }
          case 100: break;
          case 15: 
            { return symbol(Sym.MINUS);
            }
          case 101: break;
          case 16: 
            { return symbol(Sym.MOD);
            }
          case 102: break;
          case 17: 
            { return symbol(Sym.GREATERTHAN);
            }
          case 103: break;
          case 18: 
            { return symbol(Sym.LESSTHAN);
            }
          case 104: break;
          case 19: 
            { yybegin(STRING); string.setLength(0);
            }
          case 105: break;
          case 20: 
            { string.append( yytext() );
            }
          case 106: break;
          case 21: 
            { throw new RuntimeException("Unterminated string at end of line");
            }
          case 107: break;
          case 22: 
            { yybegin(YYINITIAL); return symbol(Sym.STRING_LITERAL, string.toString());
            }
          case 108: break;
          case 23: 
            { return symbol(Sym.DIVEQ);
            }
          case 109: break;
          case 24: 
            { return symbol(Sym.MULTEQ);
            }
          case 110: break;
          case 25: 
            { return symbol(Sym.DECIMAL_LITERAL, new Double(yytext()));
            }
          case 111: break;
          case 26: 
            { return symbol(Sym.OF);
            }
          case 112: break;
          case 27: 
            { return symbol(Sym.AS);
            }
          case 113: break;
          case 28: 
            { return symbol(Sym.IF);
            }
          case 114: break;
          case 29: 
            { return symbol(Sym.IN);
            }
          case 115: break;
          case 30: 
            { return symbol(Sym.DO);
            }
          case 116: break;
          case 31: 
            { return symbol(Sym.TO);
            }
          case 117: break;
          case 32: 
            { return symbol(Sym.EQUALS);
            }
          case 118: break;
          case 33: 
            { return symbol(Sym.PLUSEQ);
            }
          case 119: break;
          case 34: 
            { return symbol(Sym.PLUSPLUS);
            }
          case 120: break;
          case 35: 
            { return symbol(Sym.MINUSEQ);
            }
          case 121: break;
          case 36: 
            { return symbol(Sym.MINUSMINUS);
            }
          case 122: break;
          case 37: 
            { return symbol(Sym.MODEQ);
            }
          case 123: break;
          case 38: 
            { return symbol(Sym.OR);
            }
          case 124: break;
          case 39: 
            { return symbol(Sym.GREATERTHANEQUALS);
            }
          case 125: break;
          case 40: 
            { return symbol(Sym.LESSTHANEQUALS);
            }
          case 126: break;
          case 41: 
            { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
            }
          case 127: break;
          case 42: 
            { string.append( '\\' );
            }
          case 128: break;
          case 43: 
            { string.append( '\n' );
            }
          case 129: break;
          case 44: 
            { string.append( '\f' );
            }
          case 130: break;
          case 45: 
            { string.append( '\r' );
            }
          case 131: break;
          case 46: 
            { string.append( '\t' );
            }
          case 132: break;
          case 47: 
            { string.append( '\"' );
            }
          case 133: break;
          case 48: 
            { string.append( '\b' );
            }
          case 134: break;
          case 49: 
            { string.append( '\'' );
            }
          case 135: break;
          case 50: 
            { return symbol(Sym.FOR);
            }
          case 136: break;
          case 51: 
            { return symbol(Sym.END);
            }
          case 137: break;
          case 52: 
            { return symbol(Sym.NOT);
            }
          case 138: break;
          case 53: 
            { return symbol(Sym.AND);
            }
          case 139: break;
          case 54: 
            { return symbol(Sym.BOOLEAN_LITERAL, true);
            }
          case 140: break;
          case 55: 
            { return symbol(Sym.ELSE);
            }
          case 141: break;
          case 56: 
            { return symbol(Sym.STEP);
            }
          case 142: break;
          case 57: 
            { return symbol(Sym.LIST);
            }
          case 143: break;
          case 58: 
            { return symbol(Sym.NULL_LITERAL);
            }
          case 144: break;
          case 59: 
            { return symbol(Sym.CASE);
            }
          case 145: break;
          case 60: 
            { return symbol(Sym.THEN);
            }
          case 146: break;
          case 61: 
            { return symbol(Sym.VOID);
            }
          case 147: break;
          case 62: 
            { return symbol(Sym.BEGIN);
            }
          case 148: break;
          case 63: 
            { return symbol(Sym.BOOLEAN_LITERAL, false);
            }
          case 149: break;
          case 64: 
            { return symbol(Sym.WHILE);
            }
          case 150: break;
          case 65: 
            { return symbol(Sym.FORCE);
            }
          case 151: break;
          case 66: 
            { return symbol(Sym.COORD);
            }
          case 152: break;
          case 67: 
            { return symbol(Sym.GROUP);
            }
          case 153: break;
          case 68: 
            { return symbol(Sym.DOWNTO);
            }
          case 154: break;
          case 69: 
            { return symbol(Sym.STRING);
            }
          case 155: break;
          case 70: 
            { return symbol(Sym.SWITCH);
            }
          case 156: break;
          case 71: 
            { return symbol(Sym.RETURN);
            }
          case 157: break;
          case 72: 
            { return symbol(Sym.VECTOR);
            }
          case 158: break;
          case 73: 
            { return symbol(Sym.BOOLEAN);
            }
          case 159: break;
          case 74: 
            { return symbol(Sym.BARRIER);
            }
          case 160: break;
          case 75: 
            { return symbol(Sym.DEFAULT);
            }
          case 161: break;
          case 76: 
            { return symbol(Sym.DECLARE);
            }
          case 162: break;
          case 77: 
            { return symbol(Sym.DECIMAL);
            }
          case 163: break;
          case 78: 
            { return symbol(Sym.FOREACH);
            }
          case 164: break;
          case 79: 
            { return symbol(Sym.PLATOON);
            }
          case 165: break;
          case 80: 
            { return symbol(Sym.PROGRAM);
            }
          case 166: break;
          case 81: 
            { return symbol(Sym.SOLDIER);
            }
          case 167: break;
          case 82: 
            { return symbol(Sym.TERRAIN);
            }
          case 168: break;
          case 83: 
            { return symbol(Sym.FUNCTION);
            }
          case 169: break;
          case 84: 
            { return symbol(Sym.INTERRUPTS);
            }
          case 170: break;
          case 85: 
            { return symbol(Sym.SIMULATION);
            }
          case 171: break;
          case 86: 
            { return symbol(Sym.DECLARATIONS);
            }
          case 172: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
