/* The following code was generated by JFlex 1.4.3 on 3/10/16 7:53 PM */

package com.company;

import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 3/10/16 7:53 PM from the specification file
 * <tt>battlesim.jflex</tt>
 */
class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\0\1\76"+
    "\2\0\1\70\1\0\1\77\1\60\1\61\1\5\1\66\1\64\1\67"+
    "\1\11\1\4\1\7\11\10\2\0\1\52\1\65\1\53\2\0\1\71"+
    "\1\13\1\56\1\26\1\34\1\27\1\74\1\75\1\21\2\12\1\51"+
    "\1\12\1\45\1\72\1\37\1\73\1\50\1\47\1\41\1\55\1\57"+
    "\1\23\3\12\1\62\1\6\1\63\1\0\1\12\1\0\1\17\1\46"+
    "\1\31\1\35\1\16\1\22\1\36\1\24\1\25\2\12\1\15\1\40"+
    "\1\20\1\14\1\43\1\12\1\30\1\44\1\33\1\32\1\12\1\54"+
    "\1\12\1\42\1\12\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\2\5\1\6\20\7"+
    "\1\10\1\11\2\7\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\3\7\1\23\1\24\2\25"+
    "\1\1\1\26\1\2\1\0\1\27\1\30\2\0\1\31"+
    "\2\7\1\32\1\33\1\34\2\7\1\35\10\7\1\36"+
    "\14\7\1\37\1\40\1\41\1\42\1\43\1\7\1\44"+
    "\1\7\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\2\0\10\7\1\56\3\7\1\57\6\7"+
    "\1\60\7\7\1\61\1\7\1\0\13\7\1\62\1\63"+
    "\2\7\1\64\1\65\1\7\1\66\3\7\1\67\1\7"+
    "\1\70\1\71\2\7\1\72\1\7\1\73\1\74\20\7"+
    "\1\75\1\7\1\76\3\7\1\77\1\7\1\100\1\101"+
    "\1\102\1\103\2\7\1\104\1\105\1\106\1\107\1\110"+
    "\1\7\1\111\2\7\1\112\1\113\6\7\1\114\4\7"+
    "\1\115\3\7\1\116";

  private static int [] zzUnpackAction() {
    int [] result = new int[222];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\100\0\200\0\300\0\200\0\u0100\0\u0140\0\u0180"+
    "\0\u01c0\0\u0200\0\u0240\0\u0280\0\u02c0\0\u0300\0\u0340\0\u0380"+
    "\0\u03c0\0\u0400\0\u0440\0\u0480\0\u04c0\0\u0500\0\u0540\0\u0580"+
    "\0\u05c0\0\u0600\0\200\0\200\0\u0640\0\u0680\0\200\0\200"+
    "\0\200\0\200\0\200\0\200\0\u06c0\0\u0700\0\u0740\0\u0780"+
    "\0\u07c0\0\u0800\0\200\0\u0840\0\u0880\0\200\0\u08c0\0\200"+
    "\0\u0900\0\u0940\0\200\0\200\0\u0180\0\u0200\0\u0200\0\u0980"+
    "\0\u09c0\0\u0240\0\u0a00\0\u0240\0\u0a40\0\u0a80\0\u0ac0\0\u0b00"+
    "\0\u0b40\0\u0b80\0\u0bc0\0\u0c00\0\u0c40\0\u0c80\0\u0cc0\0\u0240"+
    "\0\u0d00\0\u0d40\0\u0d80\0\u0dc0\0\u0e00\0\u0e40\0\u0e80\0\u0ec0"+
    "\0\u0f00\0\u0f40\0\u0f80\0\u0fc0\0\200\0\200\0\200\0\200"+
    "\0\200\0\u1000\0\u0240\0\u1040\0\200\0\200\0\200\0\200"+
    "\0\200\0\200\0\200\0\200\0\200\0\u1080\0\u10c0\0\u1100"+
    "\0\u1140\0\u1180\0\u11c0\0\u1200\0\u1240\0\u1280\0\u12c0\0\u1300"+
    "\0\u1340\0\u1380\0\u13c0\0\u0240\0\u1400\0\u1440\0\u1480\0\u14c0"+
    "\0\u1500\0\u1540\0\u0240\0\u1580\0\u15c0\0\u1600\0\u1640\0\u1680"+
    "\0\u16c0\0\u1700\0\u0240\0\u1740\0\u1780\0\u17c0\0\u1800\0\u1840"+
    "\0\u1880\0\u18c0\0\u1900\0\u1940\0\u1980\0\u19c0\0\u1a00\0\u1a40"+
    "\0\u0240\0\u0240\0\u1a80\0\u1ac0\0\u0240\0\u0240\0\u1b00\0\u0240"+
    "\0\u1b40\0\u1b80\0\u1bc0\0\u0240\0\u1c00\0\u0240\0\u0240\0\u1c40"+
    "\0\u1c80\0\u0240\0\u1cc0\0\u0240\0\u0240\0\u1d00\0\u1d40\0\u1d80"+
    "\0\u1dc0\0\u1e00\0\u1e40\0\u1e80\0\u1ec0\0\u1f00\0\u1f40\0\u1f80"+
    "\0\u1fc0\0\u2000\0\u2040\0\u2080\0\u20c0\0\u0240\0\u2100\0\u0240"+
    "\0\u2140\0\u2180\0\u21c0\0\u0240\0\u2200\0\u0240\0\u0240\0\u0240"+
    "\0\u0240\0\u2240\0\u2280\0\u0240\0\u0240\0\u0240\0\u0240\0\u0240"+
    "\0\u22c0\0\u0240\0\u2300\0\u2340\0\u0240\0\u2380\0\u23c0\0\u2400"+
    "\0\u2440\0\u2480\0\u24c0\0\u2500\0\u2540\0\u2580\0\u25c0\0\u2600"+
    "\0\u2640\0\u0240\0\u2680\0\u26c0\0\u2700\0\u0240";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[222];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\7\1\3\1\10\1\11"+
    "\1\12\1\13\1\14\3\13\1\15\1\13\1\16\1\17"+
    "\1\20\2\13\1\21\1\22\3\13\1\23\1\24\2\13"+
    "\1\25\1\13\1\26\3\13\1\27\1\13\1\30\1\31"+
    "\1\32\1\33\1\34\2\13\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\13\1\52\1\13\1\53\1\3\1\54\1\55"+
    "\1\56\3\54\1\57\67\54\1\60\1\54\102\0\1\5"+
    "\101\0\1\61\1\62\57\0\1\63\77\0\1\64\21\0"+
    "\2\65\1\66\75\0\2\11\1\66\75\0\2\67\76\0"+
    "\2\13\1\0\40\13\2\0\4\13\11\0\5\13\11\0"+
    "\2\13\1\0\2\13\1\70\1\13\1\71\33\13\2\0"+
    "\4\13\11\0\5\13\11\0\2\13\1\0\32\13\1\72"+
    "\5\13\2\0\4\13\11\0\5\13\11\0\2\13\1\0"+
    "\6\13\1\73\1\13\1\74\27\13\2\0\4\13\11\0"+
    "\5\13\11\0\2\13\1\0\5\13\1\75\32\13\2\0"+
    "\4\13\11\0\5\13\11\0\2\13\1\0\12\13\1\76"+
    "\25\13\2\0\4\13\11\0\5\13\11\0\2\13\1\0"+
    "\2\13\1\77\1\13\1\100\33\13\2\0\4\13\11\0"+
    "\5\13\11\0\2\13\1\0\2\13\1\101\15\13\1\102"+
    "\17\13\2\0\4\13\11\0\5\13\11\0\2\13\1\0"+
    "\16\13\1\103\21\13\2\0\4\13\11\0\5\13\11\0"+
    "\2\13\1\0\3\13\1\104\2\13\1\105\31\13\2\0"+
    "\4\13\11\0\2\13\1\106\2\13\11\0\2\13\1\0"+
    "\16\13\1\107\21\13\2\0\4\13\11\0\5\13\11\0"+
    "\2\13\1\0\2\13\1\110\7\13\1\111\15\13\1\112"+
    "\7\13\2\0\4\13\11\0\5\13\11\0\2\13\1\0"+
    "\20\13\1\113\17\13\2\0\1\13\1\114\2\13\11\0"+
    "\1\13\1\115\3\13\11\0\2\13\1\0\21\13\1\116"+
    "\16\13\2\0\1\117\3\13\11\0\5\13\11\0\2\13"+
    "\1\0\4\13\1\120\33\13\2\0\4\13\11\0\5\13"+
    "\11\0\2\13\1\0\13\13\1\121\6\13\1\122\15\13"+
    "\2\0\4\13\11\0\5\13\11\0\2\13\1\0\5\13"+
    "\1\123\32\13\2\0\4\13\11\0\5\13\11\0\2\13"+
    "\1\0\2\13\1\124\35\13\2\0\4\13\11\0\5\13"+
    "\67\0\1\125\1\126\76\0\1\127\1\0\1\130\75\0"+
    "\1\131\21\0\2\13\1\0\33\13\1\132\4\13\2\0"+
    "\4\13\11\0\5\13\11\0\2\13\1\0\36\13\1\133"+
    "\1\13\2\0\4\13\11\0\5\13\11\0\2\13\1\0"+
    "\36\13\1\134\1\13\2\0\4\13\11\0\5\13\2\0"+
    "\1\54\2\0\3\54\1\0\67\54\1\0\1\54\2\0"+
    "\1\56\75\0\2\135\1\0\3\135\1\136\11\135\1\137"+
    "\1\135\1\140\5\135\1\141\2\135\1\142\12\135\1\143"+
    "\27\135\1\144\1\145\1\61\1\4\1\5\75\61\5\146"+
    "\1\147\72\146\7\0\2\13\1\0\2\13\1\150\35\13"+
    "\2\0\4\13\11\0\5\13\11\0\2\13\1\0\24\13"+
    "\1\151\13\13\2\0\4\13\11\0\5\13\11\0\2\13"+
    "\1\0\17\13\1\152\20\13\2\0\4\13\11\0\5\13"+
    "\11\0\2\13\1\0\3\13\1\153\34\13\2\0\4\13"+
    "\11\0\5\13\11\0\2\13\1\0\13\13\1\154\24\13"+
    "\2\0\4\13\11\0\5\13\11\0\2\13\1\0\40\13"+
    "\2\0\1\155\3\13\11\0\5\13\11\0\2\13\1\0"+
    "\10\13\1\156\6\13\1\157\20\13\2\0\4\13\11\0"+
    "\5\13\11\0\2\13\1\0\16\13\1\160\21\13\2\0"+
    "\4\13\11\0\5\13\11\0\2\13\1\0\6\13\1\161"+
    "\31\13\2\0\4\13\11\0\5\13\11\0\2\13\1\0"+
    "\20\13\1\162\17\13\2\0\4\13\11\0\5\13\11\0"+
    "\2\13\1\0\32\13\1\163\5\13\2\0\4\13\11\0"+
    "\5\13\11\0\2\13\1\0\23\13\1\164\14\13\2\0"+
    "\4\13\11\0\5\13\11\0\2\13\1\0\40\13\2\0"+
    "\1\13\1\165\2\13\11\0\5\13\11\0\2\13\1\0"+
    "\2\13\1\166\35\13\2\0\4\13\11\0\5\13\11\0"+
    "\2\13\1\0\4\13\1\167\33\13\2\0\4\13\11\0"+
    "\5\13\11\0\2\13\1\0\31\13\1\170\6\13\2\0"+
    "\4\13\11\0\5\13\11\0\2\13\1\0\26\13\1\171"+
    "\11\13\2\0\4\13\11\0\5\13\11\0\2\13\1\0"+
    "\37\13\1\172\2\0\4\13\11\0\5\13\11\0\2\13"+
    "\1\0\27\13\1\173\10\13\2\0\4\13\11\0\5\13"+
    "\11\0\2\13\1\0\16\13\1\174\21\13\2\0\4\13"+
    "\11\0\5\13\11\0\2\13\1\0\13\13\1\175\24\13"+
    "\2\0\4\13\11\0\5\13\11\0\2\13\1\0\21\13"+
    "\1\176\16\13\2\0\4\13\11\0\5\13\11\0\2\13"+
    "\1\0\32\13\1\177\5\13\2\0\4\13\11\0\5\13"+
    "\11\0\2\13\1\0\35\13\1\200\2\13\2\0\4\13"+
    "\11\0\5\13\11\0\2\13\1\0\32\13\1\201\5\13"+
    "\2\0\4\13\11\0\5\13\11\0\2\13\1\0\13\13"+
    "\1\202\24\13\2\0\4\13\11\0\5\13\11\0\2\13"+
    "\1\0\14\13\1\203\23\13\2\0\4\13\11\0\5\13"+
    "\11\0\2\13\1\0\22\13\1\204\15\13\2\0\4\13"+
    "\11\0\5\13\2\0\5\146\1\205\72\146\4\0\1\5"+
    "\1\147\101\0\2\13\1\0\3\13\1\206\34\13\2\0"+
    "\4\13\11\0\5\13\11\0\2\13\1\0\13\13\1\207"+
    "\24\13\2\0\4\13\11\0\5\13\11\0\2\13\1\0"+
    "\3\13\1\210\34\13\2\0\4\13\11\0\5\13\11\0"+
    "\2\13\1\0\32\13\1\211\5\13\2\0\4\13\11\0"+
    "\5\13\11\0\2\13\1\0\3\13\1\212\34\13\2\0"+
    "\4\13\11\0\5\13\11\0\2\13\1\0\6\13\1\213"+
    "\31\13\2\0\4\13\11\0\5\13\11\0\2\13\1\0"+
    "\5\13\1\214\5\13\1\215\24\13\2\0\4\13\11\0"+
    "\5\13\11\0\2\13\1\0\3\13\1\216\34\13\2\0"+
    "\4\13\11\0\5\13\11\0\2\13\1\0\4\13\1\217"+
    "\33\13\2\0\4\13\11\0\5\13\11\0\2\13\1\0"+
    "\17\13\1\220\20\13\2\0\4\13\11\0\5\13\11\0"+
    "\2\13\1\0\4\13\1\221\33\13\2\0\4\13\11\0"+
    "\5\13\11\0\2\13\1\0\4\13\1\222\33\13\2\0"+
    "\4\13\11\0\5\13\11\0\2\13\1\0\40\13\2\0"+
    "\4\13\11\0\1\223\4\13\11\0\2\13\1\0\24\13"+
    "\1\224\13\13\2\0\4\13\11\0\5\13\11\0\2\13"+
    "\1\0\6\13\1\225\31\13\2\0\4\13\11\0\5\13"+
    "\11\0\2\13\1\0\4\13\1\226\33\13\2\0\4\13"+
    "\11\0\5\13\11\0\2\13\1\0\34\13\1\227\3\13"+
    "\2\0\4\13\11\0\5\13\11\0\2\13\1\0\37\13"+
    "\1\230\2\0\4\13\11\0\5\13\11\0\2\13\1\0"+
    "\13\13\1\231\24\13\2\0\4\13\11\0\5\13\11\0"+
    "\2\13\1\0\21\13\1\232\16\13\2\0\4\13\11\0"+
    "\5\13\11\0\2\13\1\0\20\13\1\233\17\13\2\0"+
    "\4\13\11\0\5\13\11\0\2\13\1\0\21\13\1\234"+
    "\16\13\2\0\4\13\11\0\5\13\11\0\2\13\1\0"+
    "\35\13\1\235\2\13\2\0\4\13\11\0\5\13\11\0"+
    "\2\13\1\0\4\13\1\236\33\13\2\0\4\13\11\0"+
    "\5\13\11\0\2\13\1\0\23\13\1\237\14\13\2\0"+
    "\4\13\11\0\5\13\11\0\2\13\1\0\40\13\2\0"+
    "\4\13\11\0\1\240\4\13\2\0\4\146\1\5\1\205"+
    "\72\146\7\0\2\13\1\0\4\13\1\241\33\13\2\0"+
    "\4\13\11\0\5\13\11\0\2\13\1\0\6\13\1\242"+
    "\31\13\2\0\4\13\11\0\5\13\11\0\2\13\1\0"+
    "\20\13\1\243\17\13\2\0\4\13\11\0\5\13\11\0"+
    "\2\13\1\0\4\13\1\244\33\13\2\0\4\13\11\0"+
    "\5\13\11\0\2\13\1\0\4\13\1\245\33\13\2\0"+
    "\4\13\11\0\5\13\11\0\2\13\1\0\27\13\1\246"+
    "\10\13\2\0\4\13\11\0\5\13\11\0\2\13\1\0"+
    "\20\13\1\247\17\13\2\0\4\13\11\0\5\13\11\0"+
    "\2\13\1\0\6\13\1\250\31\13\2\0\4\13\11\0"+
    "\5\13\11\0\2\13\1\0\5\13\1\251\32\13\2\0"+
    "\4\13\11\0\5\13\11\0\2\13\1\0\5\13\1\252"+
    "\32\13\2\0\4\13\11\0\5\13\11\0\2\13\1\0"+
    "\21\13\1\253\16\13\2\0\4\13\11\0\5\13\11\0"+
    "\2\13\1\0\37\13\1\254\2\0\4\13\11\0\5\13"+
    "\11\0\2\13\1\0\16\13\1\255\21\13\2\0\4\13"+
    "\11\0\5\13\11\0\2\13\1\0\4\13\1\256\33\13"+
    "\2\0\4\13\11\0\5\13\11\0\2\13\1\0\6\13"+
    "\1\257\31\13\2\0\4\13\11\0\5\13\11\0\2\13"+
    "\1\0\17\13\1\260\20\13\2\0\4\13\11\0\5\13"+
    "\11\0\2\13\1\0\16\13\1\261\21\13\2\0\4\13"+
    "\11\0\5\13\11\0\2\13\1\0\27\13\1\262\10\13"+
    "\2\0\4\13\11\0\5\13\11\0\2\13\1\0\27\13"+
    "\1\263\10\13\2\0\4\13\11\0\5\13\11\0\2\13"+
    "\1\0\5\13\1\264\32\13\2\0\4\13\11\0\5\13"+
    "\11\0\2\13\1\0\23\13\1\265\14\13\2\0\4\13"+
    "\11\0\5\13\11\0\2\13\1\0\2\13\1\266\35\13"+
    "\2\0\4\13\11\0\5\13\11\0\2\13\1\0\3\13"+
    "\1\267\34\13\2\0\4\13\11\0\5\13\11\0\2\13"+
    "\1\0\4\13\1\270\33\13\2\0\4\13\11\0\5\13"+
    "\11\0\2\13\1\0\16\13\1\271\21\13\2\0\4\13"+
    "\11\0\5\13\11\0\2\13\1\0\17\13\1\272\20\13"+
    "\2\0\4\13\11\0\5\13\11\0\2\13\1\0\13\13"+
    "\1\273\24\13\2\0\4\13\11\0\5\13\11\0\2\13"+
    "\1\0\35\13\1\274\2\13\2\0\4\13\11\0\5\13"+
    "\11\0\2\13\1\0\5\13\1\275\32\13\2\0\4\13"+
    "\11\0\5\13\11\0\2\13\1\0\16\13\1\276\21\13"+
    "\2\0\4\13\11\0\5\13\11\0\2\13\1\0\24\13"+
    "\1\277\13\13\2\0\4\13\11\0\5\13\11\0\2\13"+
    "\1\0\12\13\1\300\25\13\2\0\4\13\11\0\5\13"+
    "\11\0\2\13\1\0\6\13\1\301\31\13\2\0\4\13"+
    "\11\0\5\13\11\0\2\13\1\0\40\13\2\0\4\13"+
    "\11\0\4\13\1\302\11\0\2\13\1\0\22\13\1\303"+
    "\15\13\2\0\4\13\11\0\5\13\11\0\2\13\1\0"+
    "\6\13\1\304\31\13\2\0\4\13\11\0\5\13\11\0"+
    "\2\13\1\0\4\13\1\305\33\13\2\0\4\13\11\0"+
    "\5\13\11\0\2\13\1\0\21\13\1\306\16\13\2\0"+
    "\4\13\11\0\5\13\11\0\2\13\1\0\4\13\1\307"+
    "\33\13\2\0\4\13\11\0\5\13\11\0\2\13\1\0"+
    "\12\13\1\310\25\13\2\0\4\13\11\0\5\13\11\0"+
    "\2\13\1\0\2\13\1\311\35\13\2\0\4\13\11\0"+
    "\5\13\11\0\2\13\1\0\26\13\1\312\11\13\2\0"+
    "\4\13\11\0\5\13\11\0\2\13\1\0\40\13\2\0"+
    "\4\13\11\0\1\313\4\13\11\0\2\13\1\0\36\13"+
    "\1\314\1\13\2\0\4\13\11\0\5\13\11\0\2\13"+
    "\1\0\6\13\1\315\31\13\2\0\4\13\11\0\5\13"+
    "\11\0\2\13\1\0\33\13\1\316\4\13\2\0\4\13"+
    "\11\0\5\13\11\0\2\13\1\0\27\13\1\317\10\13"+
    "\2\0\4\13\11\0\5\13\11\0\2\13\1\0\22\13"+
    "\1\320\15\13\2\0\4\13\11\0\5\13\11\0\2\13"+
    "\1\0\40\13\2\0\4\13\11\0\4\13\1\321\11\0"+
    "\2\13\1\0\40\13\2\0\4\13\11\0\2\13\1\322"+
    "\2\13\11\0\2\13\1\0\40\13\2\0\4\13\11\0"+
    "\1\323\4\13\11\0\2\13\1\0\40\13\2\0\1\13"+
    "\1\324\2\13\11\0\5\13\11\0\2\13\1\0\33\13"+
    "\1\325\4\13\2\0\4\13\11\0\5\13\11\0\2\13"+
    "\1\0\40\13\2\0\4\13\11\0\1\326\4\13\11\0"+
    "\2\13\1\0\22\13\1\327\15\13\2\0\4\13\11\0"+
    "\5\13\11\0\2\13\1\0\37\13\1\330\2\0\4\13"+
    "\11\0\5\13\11\0\2\13\1\0\40\13\2\0\4\13"+
    "\11\0\2\13\1\331\2\13\11\0\2\13\1\0\35\13"+
    "\1\332\2\13\2\0\4\13\11\0\5\13\11\0\2\13"+
    "\1\0\40\13\2\0\1\13\1\333\2\13\11\0\5\13"+
    "\11\0\2\13\1\0\40\13\2\0\4\13\11\0\1\334"+
    "\4\13\11\0\2\13\1\0\37\13\1\335\2\0\4\13"+
    "\11\0\5\13\11\0\2\13\1\0\35\13\1\336\2\13"+
    "\2\0\4\13\11\0\5\13\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10048];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\25\1\2\11\2\1\6\11"+
    "\6\1\1\11\2\1\1\11\1\1\1\11\1\1\1\0"+
    "\2\11\2\0\36\1\5\11\3\1\11\11\2\0\35\1"+
    "\1\0\131\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[222];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
      StringBuffer string = new StringBuffer();

      private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
      }
      private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
      }

      /* This is required, as ZZAtEOF is private */
      public boolean getZZAtEOF() {
        return zzAtEOF;
      }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 168) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 75: 
          { return symbol(Token.LESSTHAN);
          }
        case 79: break;
        case 1: 
          { throw new RuntimeException("Illegal character \""+yytext()+"\" at line "+yyline+", column "+yycolumn);
          }
        case 80: break;
        case 48: 
          { return symbol(Token.NOT);
          }
        case 81: break;
        case 9: 
          { return symbol(Token.RANGLE);
          }
        case 82: break;
        case 19: 
          { yybegin(STRING); string.setLength(0);
          }
        case 83: break;
        case 76: 
          { return symbol(Token.GREATERTHAN);
          }
        case 84: break;
        case 28: 
          { return symbol(Token.IF);
          }
        case 85: break;
        case 74: 
          { return symbol(Token.FUNCTION);
          }
        case 86: break;
        case 23: 
          { return symbol(Token.DIVEQ);
          }
        case 87: break;
        case 30: 
          { return symbol(Token.TO);
          }
        case 88: break;
        case 7: 
          { return symbol(Token.IDENTIFIER, yytext());
          }
        case 89: break;
        case 62: 
          { return symbol(Token.DEFINE);
          }
        case 90: break;
        case 16: 
          { return symbol(Token.PLUS);
          }
        case 91: break;
        case 8: 
          { return symbol(Token.LANGLE);
          }
        case 92: break;
        case 42: 
          { string.append( '\t' );
          }
        case 93: break;
        case 70: 
          { return symbol(Token.DEFAULT);
          }
        case 94: break;
        case 47: 
          { return symbol(Token.END);
          }
        case 95: break;
        case 72: 
          { return symbol(Token.FOREACH);
          }
        case 96: break;
        case 69: 
          { return symbol(Token.INCLUDE);
          }
        case 97: break;
        case 52: 
          { return symbol(Token.THEN);
          }
        case 98: break;
        case 33: 
          { return symbol(Token.MINUSEQ);
          }
        case 99: break;
        case 78: 
          { return symbol(Token.GREATERTHANEQUALS);
          }
        case 100: break;
        case 5: 
          { return symbol(Token.INTEGER_LITERAL, new Integer(yytext()));
          }
        case 101: break;
        case 31: 
          { return symbol(Token.PLUSEQ);
          }
        case 102: break;
        case 39: 
          { string.append( '\n' );
          }
        case 103: break;
        case 17: 
          { return symbol(Token.MINUS);
          }
        case 104: break;
        case 65: 
          { return symbol(Token.STRING);
          }
        case 105: break;
        case 13: 
          { return symbol(Token.RBRACE);
          }
        case 106: break;
        case 32: 
          { return symbol(Token.PLUSPLUS);
          }
        case 107: break;
        case 34: 
          { return symbol(Token.MINUSMINUS);
          }
        case 108: break;
        case 54: 
          { return symbol(Token.NULL_LITERAL);
          }
        case 109: break;
        case 77: 
          { return symbol(Token.LESSTHANEQUALS);
          }
        case 110: break;
        case 67: 
          { return symbol(Token.RETURN);
          }
        case 111: break;
        case 26: 
          { return symbol(Token.AS);
          }
        case 112: break;
        case 25: 
          { return symbol(Token.NUMBER_LITERAL, new Double(yytext()));
          }
        case 113: break;
        case 2: 
          { /* nothing happens here, maybe */
          }
        case 114: break;
        case 37: 
          { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
          }
        case 115: break;
        case 60: 
          { return symbol(Token.WHILE);
          }
        case 116: break;
        case 12: 
          { return symbol(Token.LBRACE);
          }
        case 117: break;
        case 41: 
          { string.append( '\r' );
          }
        case 118: break;
        case 56: 
          { return symbol(Token.CASE);
          }
        case 119: break;
        case 59: 
          { return symbol(Token.BOOLEAN_LITERAL, false);
          }
        case 120: break;
        case 14: 
          { return symbol(Token.COMMA);
          }
        case 121: break;
        case 43: 
          { string.append( '\b' );
          }
        case 122: break;
        case 46: 
          { return symbol(Token.FOR);
          }
        case 123: break;
        case 21: 
          { throw new RuntimeException("Unterminated string at end of line");
          }
        case 124: break;
        case 53: 
          { return symbol(Token.TYPE);
          }
        case 125: break;
        case 44: 
          { string.append( '\"' );
          }
        case 126: break;
        case 15: 
          { return symbol(Token.EQ);
          }
        case 127: break;
        case 50: 
          { return symbol(Token.BOOLEAN_LITERAL, true);
          }
        case 128: break;
        case 29: 
          { return symbol(Token.DO);
          }
        case 129: break;
        case 57: 
          { return symbol(Token.VOID);
          }
        case 130: break;
        case 11: 
          { return symbol(Token.RPAREN);
          }
        case 131: break;
        case 22: 
          { yybegin(YYINITIAL); return symbol(Token.STRING_LITERAL, string.toString());
          }
        case 132: break;
        case 45: 
          { string.append( '\'' );
          }
        case 133: break;
        case 38: 
          { string.append( '\\' );
          }
        case 134: break;
        case 3: 
          { return symbol(Token.DIV);
          }
        case 135: break;
        case 4: 
          { return symbol(Token.MULT);
          }
        case 136: break;
        case 24: 
          { return symbol(Token.MULTEQ);
          }
        case 137: break;
        case 18: 
          { return symbol(Token.MOD);
          }
        case 138: break;
        case 73: 
          { return symbol(Token.PROGRAM);
          }
        case 139: break;
        case 35: 
          { return symbol(Token.MODEQ);
          }
        case 140: break;
        case 64: 
          { return symbol(Token.NUMBER);
          }
        case 141: break;
        case 51: 
          { return symbol(Token.ELSE);
          }
        case 142: break;
        case 63: 
          { return symbol(Token.EQUALS);
          }
        case 143: break;
        case 40: 
          { string.append( '\f' );
          }
        case 144: break;
        case 71: 
          { return symbol(Token.DECLARE);
          }
        case 145: break;
        case 27: 
          { return symbol(Token.IN);
          }
        case 146: break;
        case 58: 
          { return symbol(Token.BEGIN);
          }
        case 147: break;
        case 36: 
          { return symbol(Token.OR);
          }
        case 148: break;
        case 20: 
          { string.append( yytext() );
          }
        case 149: break;
        case 10: 
          { return symbol(Token.LPAREN);
          }
        case 150: break;
        case 68: 
          { return symbol(Token.BOOLEAN);
          }
        case 151: break;
        case 6: 
          { return symbol(Token.DOT);
          }
        case 152: break;
        case 61: 
          { return symbol(Token.DOWNTO);
          }
        case 153: break;
        case 49: 
          { return symbol(Token.AND);
          }
        case 154: break;
        case 55: 
          { return symbol(Token.LIST);
          }
        case 155: break;
        case 66: 
          { return symbol(Token.SWITCH);
          }
        case 156: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(Token.EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
