// Test declerations
// Declarations er påkrævet
// TEST: Success
Begin Declarations
    Declare da as Boolean
    Declare no as Boolean
    Declare k as Decimal
    Declare foo as Integer
    Declare s as String
    Declare a as Integer
    Declare list as List of String
    Declare i as Integer
    i = 5
    Declare Charlie as Soldier
End Declarations

// Test Include
// Include kan først komme efter simulations og declerations
//  ellers gives fejl
// TEST: Success
#Include("stdlib.bsi")
#Include("test_functions.bsi") // Include all
                               // our test functions

Begin Program

    /*
        Testing block comment
    */
    // Run test for reccursiv functions
    PrintLine(Factorial(5) + "")
    PrintLine("Factorial success")

    // Run test for return Integer
    PrintLine(ReturnInt() + "")
    PrintLine("return Integer success")

    // Run test for return Decimal
    PrintLine(ReturnDecimal() + "")
    PrintLine("return dedimal success")

    // Run test for while
    TestWhile()
    PrintLine("while success")

    // Test array and Foreach
    TestArrayForeach()
    PrintLine("array and foreach success")

    // Test math
    math(12)
    PrintLine("math tested success")

    // Test bool
    TestBool()
    PrintLine("bool tested success")

    // Test if
    TestIf()
    PrintLine("If tested success")

    TestSwitch()
    PrintLine("Switch tested success")

    TestFor()
    PrintLine("For loops tested success")

    // Ej muligt
    //PrintLine("Test \"escape\"...")
    // Test \n. \n virker kun med workaround #15
    Print("New line \\n")

    Print("Test print")
    PrintLine("")

    TestScope()


End Program