
Function Void PrintHelloWorld(t as String)
	%``.limit stack 2
	%``getstatic java/lang/System/out Ljava/io/PrintStream;
    %``ldc "Hello World!"
    %``invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
    %``return
End Function

Begin Declarations
End Declarations

Begin Declare Simulations
End Declare Simulations

Begin Program
  %``getstatic java/lang/System/out Ljava/io/PrintStream;
  %``ldc "Hello World!"
  %``invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
End Program
