Begin Declarations
    Declare da as Boolean
    Declare no as Boolean
End Declarations

Declare Simulations
End Declare Simulations

#Include("stdlib.bsi")

Function Void TestBool()
    no = false
    da = true

    PrintLine(no + "")
    PrintLine(da + "")

    PrintLine((da AND da) + "")
    PrintLine((no AND no) + "")
    PrintLine((da AND no) + "")

    PrintLine((da OR da) + "")
    PrintLine((no OR no) + "")
    PrintLine((da OR no) + "")

    PrintLine((NOT da AND da) + "")
    PrintLine((NOT no AND da) + "")
    PrintLine((NOT no AND NOT no) + "")
    PrintLine((NOT da AND NOT da) + "")

    PrintLine((NOT NOT NOT NOT NOT no) + "")
    PrintLine((NOT NOT da OR no) + "")
    PrintLine(((NOT NOT da) OR (da AND (NOT no))) + "")
End Function

Begin Program

  TestBool()

End Program
