#Include("stdlib.bsi")

Begin Declarations
  //Declare Terrain
  Declare terrain as Terrain
  terrain.Width = 1800
  terrain.Height = 900

  //Declare Allies
  Declare aGroup1 as Group
  Declare i as Integer
  i = 0
  For i To 20 Do
    Declare aSol as Soldier
    If i < 10 Then
      aSol.Pos = (500 + i * 10, 100)
    Else
      aSol.Pos = (500 + (i - 10) * 10, 110)
    End If
    aGroup1.AddSoldier(aSol)
    i += 1
  End For

  Declare aGroup2 as Group
  i = 0
  For i To 40 Do
    Declare aSol as Soldier
    If i < 20 Then
      aSol.Pos = (700 + i * 10, 100)
    Else
      aSol.Pos = (700 + (i - 20) * 10, 110)
    End If
    aGroup2.AddSoldier(aSol)
    i += 1
  End For


  Declare allies as Force
  allies.AddGroup(aGroup1)
  allies.AddGroup(aGroup2)

  //Declare Enemies
  Declare eGroup1 as Group
  i = 0
  For i To 100 Do
    Declare eSol as Soldier
    If i < 50 Then
      eSol.Pos = (350 + i * 10, 600)
    Else
      eSol.Pos = (350 + (i - 50) * 10, 610)
    End If
    eGroup1.AddSoldier(eSol)
    i += 1
  End For

  Declare eFlank as Group
  i = 0
  For i To 40 Do
    Declare Sol as Soldier
    If i < 20 Then
      Sol.Pos = (1600 + i * 10, 20)
    Else
      Sol.Pos = (1600 + (i - 20) * 10, 30)
    End If
    eFlank.AddSoldier(Sol)
    i += 1
  End For

  Declare enemies as Force
  enemies.AddGroup(eGroup1)
  enemies.AddGroup(eFlank)

  Declare mainField as Coord
  mainField = (700, 400)
  Declare aBase as Coord
  aBase = (1800, 900)

End Declarations

Begin Declare Simulations
  Simulation AlliesSim allies
    Step 1
      aGroup1.MoveToCoord(mainField)
      aGroup2.MoveToXY(800, 400)
    Step 2
      If aGroup1.IsDead() Then
        aGroup2.MoveToCoord(aBase)
      End If
    Interrupts
  End Simulation

  Simulation EnemiesSim enemies
    Step 1
      eGroup1.MoveToCoord(mainField)
      eFlank.Wait(10)
    Step 2
      If eGroup1.CountAliveSoldiers() < 80 Then
        eFlank.MoveToCoord(mainField)
      End If
    Interrupts
  End Simulation
End Declare Simulations

Begin Program
  RunSimulation(allies, enemies, terrain, "AlliesSim", "EnemiesSim")
End Program
