/* The following code was generated by JFlex 1.6.1 */

package com.company.SyntaxAnalysis;
import java_cup.runtime.*;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>battlesim.jflex</tt>
 */
public class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\77\1\100\1\1\22\0\1\3\1\0\1\74"+
    "\2\0\1\6\1\0\1\76\1\60\1\61\1\5\1\66\1\64\1\67"+
    "\1\13\1\4\1\11\11\12\2\0\1\73\1\65\1\72\2\0\1\70"+
    "\1\15\1\55\1\30\1\36\1\31\1\57\1\14\1\23\2\14\1\51"+
    "\1\14\1\53\1\71\1\41\1\14\1\50\1\47\1\43\1\54\1\56"+
    "\1\25\3\14\1\62\1\10\1\63\1\0\1\14\1\7\1\21\1\75"+
    "\1\33\1\37\1\20\1\24\1\40\1\26\1\27\2\14\1\17\1\42"+
    "\1\22\1\16\1\45\1\14\1\32\1\46\1\35\1\34\1\14\1\52"+
    "\1\14\1\44\1\14\12\0\1\77\u1fa2\0\1\77\1\77\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\1\6\2\7"+
    "\1\10\25\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\2\11\1\22\1\23\1\24\1\25\2\26"+
    "\1\1\1\27\1\2\1\0\1\30\1\31\1\0\1\32"+
    "\2\0\1\33\3\11\1\34\1\35\1\11\1\36\2\11"+
    "\1\37\1\40\10\11\1\41\20\11\1\42\1\43\1\44"+
    "\1\45\1\46\1\11\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\2\0"+
    "\1\63\11\11\1\64\3\11\1\65\15\11\1\66\5\11"+
    "\1\67\1\0\2\63\15\11\1\70\1\71\3\11\1\72"+
    "\1\73\2\11\1\74\3\11\1\75\1\76\1\11\1\77"+
    "\1\100\3\11\1\101\3\11\1\102\1\103\5\11\1\104"+
    "\11\11\1\105\1\11\1\106\4\11\1\107\12\11\1\110"+
    "\1\111\1\112\1\113\1\114\1\115\1\11\1\116\1\117"+
    "\1\120\1\11\1\121\1\122\1\11\1\123\1\124\1\125"+
    "\1\126\3\11\1\127\4\11\1\130\1\11\1\131\1\11"+
    "\1\132\1\133";

  private static int [] zzUnpackAction() {
    int [] result = new int[259];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\101\0\202\0\303\0\202\0\202\0\u0104\0\u0145"+
    "\0\u0186\0\u01c7\0\u0208\0\u0249\0\u028a\0\u02cb\0\u030c\0\u034d"+
    "\0\u038e\0\u03cf\0\u0410\0\u0451\0\u0492\0\u04d3\0\u0514\0\u0555"+
    "\0\u0596\0\u05d7\0\u0618\0\u0659\0\u069a\0\u06db\0\u071c\0\u075d"+
    "\0\u079e\0\202\0\202\0\202\0\202\0\202\0\u07df\0\u0820"+
    "\0\u0861\0\u08a2\0\u08e3\0\u0924\0\u0965\0\202\0\u09a6\0\u09e7"+
    "\0\202\0\u0a28\0\202\0\u0a69\0\u0aaa\0\202\0\202\0\u0aeb"+
    "\0\202\0\u01c7\0\u0249\0\u0249\0\u0b2c\0\u0b6d\0\u0bae\0\u028a"+
    "\0\u028a\0\u0bef\0\u028a\0\u0c30\0\u0c71\0\u028a\0\u0cb2\0\u0cf3"+
    "\0\u0d34\0\u0d75\0\u0db6\0\u0df7\0\u0e38\0\u0e79\0\u0eba\0\u028a"+
    "\0\u0efb\0\u0f3c\0\u0f7d\0\u0fbe\0\u0fff\0\u1040\0\u1081\0\u10c2"+
    "\0\u1103\0\u1144\0\u1185\0\u11c6\0\u1207\0\u1248\0\u1289\0\u12ca"+
    "\0\202\0\202\0\202\0\202\0\202\0\u130b\0\u028a\0\202"+
    "\0\202\0\202\0\202\0\202\0\202\0\202\0\202\0\202"+
    "\0\202\0\202\0\u134c\0\u138d\0\u13ce\0\u140f\0\u1450\0\u1491"+
    "\0\u14d2\0\u1513\0\u1554\0\u1595\0\u15d6\0\u1617\0\u1658\0\u1699"+
    "\0\u16da\0\u171b\0\u028a\0\u175c\0\u179d\0\u17de\0\u181f\0\u1860"+
    "\0\u18a1\0\u18e2\0\u1923\0\u1964\0\u19a5\0\u19e6\0\u1a27\0\u1a68"+
    "\0\u028a\0\u1aa9\0\u1aea\0\u1b2b\0\u1b6c\0\u1bad\0\u028a\0\u1bee"+
    "\0\u1c2f\0\202\0\u1c70\0\u1cb1\0\u1cf2\0\u1d33\0\u1d74\0\u1db5"+
    "\0\u1df6\0\u1e37\0\u1e78\0\u1eb9\0\u1efa\0\u1f3b\0\u1f7c\0\u028a"+
    "\0\u028a\0\u1fbd\0\u1ffe\0\u203f\0\u028a\0\u028a\0\u2080\0\u20c1"+
    "\0\u028a\0\u2102\0\u2143\0\u2184\0\u028a\0\u028a\0\u21c5\0\u028a"+
    "\0\u028a\0\u2206\0\u2247\0\u2288\0\u028a\0\u22c9\0\u230a\0\u234b"+
    "\0\u028a\0\u028a\0\u238c\0\u23cd\0\u240e\0\u244f\0\u2490\0\u028a"+
    "\0\u24d1\0\u2512\0\u2553\0\u2594\0\u25d5\0\u2616\0\u2657\0\u2698"+
    "\0\u26d9\0\u028a\0\u271a\0\u028a\0\u275b\0\u279c\0\u27dd\0\u281e"+
    "\0\u028a\0\u285f\0\u28a0\0\u28e1\0\u2922\0\u2963\0\u29a4\0\u29e5"+
    "\0\u2a26\0\u2a67\0\u2aa8\0\u028a\0\u028a\0\u028a\0\u028a\0\u028a"+
    "\0\u028a\0\u2ae9\0\u028a\0\u028a\0\u028a\0\u2b2a\0\u028a\0\u028a"+
    "\0\u2b6b\0\u028a\0\u028a\0\u028a\0\u028a\0\u2bac\0\u2bed\0\u2c2e"+
    "\0\u028a\0\u2c6f\0\u2cb0\0\u2cf1\0\u2d32\0\u028a\0\u2d73\0\u2db4"+
    "\0\u2df5\0\u028a\0\u028a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[259];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\2\3"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\2\15\1\20"+
    "\1\15\1\21\1\22\1\23\1\15\1\24\1\25\1\26"+
    "\3\15\1\27\1\30\2\15\1\31\1\15\1\32\3\15"+
    "\1\33\1\34\1\35\1\15\1\36\1\15\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\15\2\3"+
    "\1\6\1\57\1\60\1\61\5\57\1\62\63\57\1\63"+
    "\4\57\103\0\1\5\102\0\1\64\1\65\57\0\1\66"+
    "\100\0\1\67\22\0\1\70\55\0\1\71\24\0\2\72"+
    "\1\73\76\0\2\13\1\73\76\0\2\74\77\0\2\15"+
    "\1\0\44\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\2\15\1\75\1\15\1\76\1\77\36\15\10\0"+
    "\2\15\3\0\1\15\14\0\2\15\1\0\10\15\1\100"+
    "\33\15\10\0\2\15\3\0\1\15\14\0\2\15\1\0"+
    "\32\15\1\101\11\15\10\0\2\15\3\0\1\15\14\0"+
    "\2\15\1\0\6\15\1\102\1\15\1\103\33\15\10\0"+
    "\2\15\3\0\1\15\14\0\2\15\1\0\5\15\1\104"+
    "\36\15\10\0\2\15\3\0\1\15\14\0\2\15\1\0"+
    "\12\15\1\105\31\15\10\0\2\15\3\0\1\15\14\0"+
    "\2\15\1\0\6\15\1\106\35\15\10\0\2\15\3\0"+
    "\1\15\14\0\2\15\1\0\2\15\1\107\1\15\1\110"+
    "\37\15\10\0\2\15\3\0\1\15\14\0\2\15\1\0"+
    "\2\15\1\111\15\15\1\112\23\15\10\0\2\15\3\0"+
    "\1\15\14\0\2\15\1\0\16\15\1\113\25\15\10\0"+
    "\2\15\3\0\1\15\14\0\2\15\1\0\3\15\1\114"+
    "\2\15\1\115\35\15\10\0\2\15\3\0\1\15\14\0"+
    "\2\15\1\0\3\15\1\116\12\15\1\117\25\15\10\0"+
    "\2\15\3\0\1\15\14\0\2\15\1\0\2\15\1\120"+
    "\1\15\1\121\5\15\1\122\15\15\1\123\13\15\10\0"+
    "\2\15\3\0\1\15\14\0\2\15\1\0\2\15\1\124"+
    "\10\15\1\125\5\15\1\126\14\15\1\127\5\15\10\0"+
    "\2\15\3\0\1\15\14\0\2\15\1\0\4\15\1\130"+
    "\37\15\10\0\2\15\3\0\1\15\14\0\2\15\1\0"+
    "\13\15\1\131\30\15\10\0\2\15\3\0\1\15\14\0"+
    "\2\15\1\0\40\15\1\132\3\15\10\0\1\15\1\133"+
    "\3\0\1\15\14\0\2\15\1\0\2\15\1\134\2\15"+
    "\1\135\36\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\2\15\1\136\1\15\1\137\37\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\16\15\1\140\25\15"+
    "\10\0\2\15\3\0\1\15\70\0\1\141\100\0\1\142"+
    "\1\143\77\0\1\144\1\0\1\145\22\0\2\15\1\0"+
    "\37\15\1\146\4\15\10\0\2\15\3\0\1\15\14\0"+
    "\2\15\1\0\34\15\1\147\7\15\10\0\2\15\3\0"+
    "\1\15\70\0\1\150\100\0\1\151\13\0\1\57\2\0"+
    "\5\57\1\0\63\57\1\0\4\57\2\0\1\61\76\0"+
    "\1\152\2\0\5\152\1\153\11\152\1\154\1\152\1\155"+
    "\5\152\1\156\2\152\1\157\36\152\1\160\1\161\1\162"+
    "\2\0\1\64\1\4\1\5\76\64\5\163\1\164\73\163"+
    "\7\0\1\165\102\0\2\15\1\0\2\15\1\166\41\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\24\15"+
    "\1\167\17\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\16\15\1\170\25\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\21\15\1\171\22\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\3\15\1\172\40\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\13\15"+
    "\1\173\30\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\36\15\1\174\5\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\10\15\1\175\6\15\1\176\24\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\16\15"+
    "\1\177\25\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\6\15\1\200\35\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\20\15\1\201\23\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\32\15\1\202\11\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\23\15"+
    "\1\203\20\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\5\15\1\204\36\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\2\15\1\205\41\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\16\15\1\206\25\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\4\15"+
    "\1\207\37\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\31\15\1\210\12\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\3\15\1\211\40\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\26\15\1\212\15\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\4\15"+
    "\1\213\11\15\1\214\25\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\13\15\1\215\30\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\21\15\1\216\22\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\32\15"+
    "\1\217\11\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\35\15\1\220\6\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\27\15\1\221\14\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\2\15\1\222\41\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\32\15"+
    "\1\223\11\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\13\15\1\224\30\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\17\15\1\225\24\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\2\15\1\226\41\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\14\15"+
    "\1\227\27\15\10\0\2\15\3\0\1\15\3\0\5\163"+
    "\1\230\73\163\4\0\1\5\1\164\73\0\1\165\1\231"+
    "\1\232\76\165\11\0\2\15\1\0\3\15\1\233\40\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\13\15"+
    "\1\234\30\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\16\15\1\235\25\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\4\15\1\236\37\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\32\15\1\237\11\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\3\15"+
    "\1\240\40\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\6\15\1\241\35\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\5\15\1\242\36\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\3\15\1\243\7\15"+
    "\1\244\30\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\4\15\1\245\12\15\1\246\24\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\17\15\1\247\24\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\4\15"+
    "\1\250\37\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\4\15\1\251\37\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\21\15\1\252\22\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\24\15\1\253\17\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\16\15"+
    "\1\254\25\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\6\15\1\255\35\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\4\15\1\256\37\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\23\15\1\257\20\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\20\15"+
    "\1\260\23\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\31\15\1\261\12\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\13\15\1\262\30\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\21\15\1\263\22\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\20\15"+
    "\1\264\23\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\21\15\1\265\22\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\35\15\1\266\6\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\16\15\1\267\25\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\4\15"+
    "\1\270\37\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\23\15\1\271\20\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\21\15\1\272\22\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\20\15\1\273\23\15"+
    "\10\0\2\15\3\0\1\15\3\0\4\163\1\5\1\230"+
    "\73\163\2\0\1\232\107\0\2\15\1\0\4\15\1\274"+
    "\37\15\10\0\2\15\3\0\1\15\14\0\2\15\1\0"+
    "\6\15\1\275\35\15\10\0\2\15\3\0\1\15\14\0"+
    "\2\15\1\0\13\15\1\276\30\15\10\0\2\15\3\0"+
    "\1\15\14\0\2\15\1\0\16\15\1\277\5\15\1\300"+
    "\17\15\10\0\2\15\3\0\1\15\14\0\2\15\1\0"+
    "\4\15\1\301\37\15\10\0\2\15\3\0\1\15\14\0"+
    "\2\15\1\0\4\15\1\302\37\15\10\0\2\15\3\0"+
    "\1\15\14\0\2\15\1\0\27\15\1\303\14\15\10\0"+
    "\2\15\3\0\1\15\14\0\2\15\1\0\20\15\1\304"+
    "\23\15\10\0\2\15\3\0\1\15\14\0\2\15\1\0"+
    "\5\15\1\305\36\15\10\0\2\15\3\0\1\15\14\0"+
    "\2\15\1\0\26\15\1\306\15\15\10\0\2\15\3\0"+
    "\1\15\14\0\2\15\1\0\5\15\1\307\36\15\10\0"+
    "\2\15\3\0\1\15\14\0\2\15\1\0\4\15\1\310"+
    "\37\15\10\0\2\15\3\0\1\15\14\0\2\15\1\0"+
    "\21\15\1\311\22\15\10\0\2\15\3\0\1\15\14\0"+
    "\2\15\1\0\2\15\1\312\41\15\10\0\2\15\3\0"+
    "\1\15\14\0\2\15\1\0\16\15\1\313\25\15\10\0"+
    "\2\15\3\0\1\15\14\0\2\15\1\0\5\15\1\314"+
    "\36\15\10\0\2\15\3\0\1\15\14\0\2\15\1\0"+
    "\13\15\1\315\30\15\10\0\2\15\3\0\1\15\14\0"+
    "\2\15\1\0\3\15\1\316\40\15\10\0\2\15\3\0"+
    "\1\15\14\0\2\15\1\0\6\15\1\317\35\15\10\0"+
    "\2\15\3\0\1\15\14\0\2\15\1\0\17\15\1\320"+
    "\24\15\10\0\2\15\3\0\1\15\14\0\2\15\1\0"+
    "\16\15\1\321\25\15\10\0\2\15\3\0\1\15\14\0"+
    "\2\15\1\0\23\15\1\322\20\15\10\0\2\15\3\0"+
    "\1\15\14\0\2\15\1\0\2\15\1\323\41\15\10\0"+
    "\2\15\3\0\1\15\14\0\2\15\1\0\31\15\1\324"+
    "\12\15\10\0\2\15\3\0\1\15\14\0\2\15\1\0"+
    "\5\15\1\325\36\15\10\0\2\15\3\0\1\15\14\0"+
    "\2\15\1\0\4\15\1\326\37\15\10\0\2\15\3\0"+
    "\1\15\14\0\2\15\1\0\16\15\1\327\25\15\10\0"+
    "\2\15\3\0\1\15\14\0\2\15\1\0\4\15\1\330"+
    "\37\15\10\0\2\15\3\0\1\15\14\0\2\15\1\0"+
    "\2\15\1\331\41\15\10\0\2\15\3\0\1\15\14\0"+
    "\2\15\1\0\3\15\1\332\40\15\10\0\2\15\3\0"+
    "\1\15\14\0\2\15\1\0\16\15\1\333\25\15\10\0"+
    "\2\15\3\0\1\15\14\0\2\15\1\0\5\15\1\334"+
    "\36\15\10\0\2\15\3\0\1\15\14\0\2\15\1\0"+
    "\17\15\1\335\24\15\10\0\2\15\3\0\1\15\14\0"+
    "\2\15\1\0\13\15\1\336\30\15\10\0\2\15\3\0"+
    "\1\15\14\0\2\15\1\0\2\15\1\337\41\15\10\0"+
    "\2\15\3\0\1\15\14\0\2\15\1\0\5\15\1\340"+
    "\36\15\10\0\2\15\3\0\1\15\14\0\2\15\1\0"+
    "\13\15\1\341\30\15\10\0\2\15\3\0\1\15\14\0"+
    "\2\15\1\0\4\15\1\342\37\15\10\0\2\15\3\0"+
    "\1\15\14\0\2\15\1\0\5\15\1\343\36\15\10\0"+
    "\2\15\3\0\1\15\14\0\2\15\1\0\24\15\1\344"+
    "\17\15\10\0\2\15\3\0\1\15\14\0\2\15\1\0"+
    "\12\15\1\345\31\15\10\0\2\15\3\0\1\15\14\0"+
    "\2\15\1\0\6\15\1\346\35\15\10\0\2\15\3\0"+
    "\1\15\14\0\2\15\1\0\16\15\1\347\25\15\10\0"+
    "\2\15\3\0\1\15\14\0\2\15\1\0\6\15\1\350"+
    "\35\15\10\0\2\15\3\0\1\15\14\0\2\15\1\0"+
    "\16\15\1\351\25\15\10\0\2\15\3\0\1\15\14\0"+
    "\2\15\1\0\20\15\1\352\23\15\10\0\2\15\3\0"+
    "\1\15\14\0\2\15\1\0\16\15\1\353\25\15\10\0"+
    "\2\15\3\0\1\15\14\0\2\15\1\0\21\15\1\354"+
    "\22\15\10\0\2\15\3\0\1\15\14\0\2\15\1\0"+
    "\4\15\1\355\1\356\36\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\3\15\1\357\40\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\12\15\1\360\31\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\2\15"+
    "\1\361\41\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\6\15\1\362\35\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\26\15\1\363\15\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\6\15\1\364\35\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\16\15"+
    "\1\365\25\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\21\15\1\366\22\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\31\15\1\367\12\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\21\15\1\370\22\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\6\15"+
    "\1\371\35\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\13\15\1\372\30\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\21\15\1\373\22\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\13\15\1\374\30\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\2\15"+
    "\1\375\41\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\32\15\1\376\11\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\2\15\1\377\41\15\10\0\2\15"+
    "\3\0\1\15\14\0\2\15\1\0\6\15\1\u0100\35\15"+
    "\10\0\2\15\3\0\1\15\14\0\2\15\1\0\6\15"+
    "\1\u0101\35\15\10\0\2\15\3\0\1\15\14\0\2\15"+
    "\1\0\32\15\1\u0102\11\15\10\0\2\15\3\0\1\15"+
    "\14\0\2\15\1\0\32\15\1\u0103\11\15\10\0\2\15"+
    "\3\0\1\15\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11830];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\2\11\33\1\5\11\7\1\1\11"+
    "\2\1\1\11\1\1\1\11\1\1\1\0\2\11\1\0"+
    "\1\11\2\0\45\1\5\11\2\1\13\11\2\0\43\1"+
    "\1\0\1\1\1\11\151\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[259];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
      StringBuffer string = new StringBuffer();

      private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
      }
      private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
      }

      /* This is required, as ZZAtEOF is private */
      public boolean getZZAtEOF() {
        return zzAtEOF;
      }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 210) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(Sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new RuntimeException("Illegal character \""+yytext()+"\" at line "+yyline+", column "+yycolumn);
            }
          case 92: break;
          case 2: 
            { return symbol(Sym.EOL);
            }
          case 93: break;
          case 3: 
            { /* nothing happens here, maybe */
            }
          case 94: break;
          case 4: 
            { return symbol(Sym.DIV);
            }
          case 95: break;
          case 5: 
            { return symbol(Sym.MULT);
            }
          case 96: break;
          case 6: 
            { return symbol(Sym.MOD);
            }
          case 97: break;
          case 7: 
            { return symbol(Sym.INTEGER_LITERAL, new Integer(yytext()));
            }
          case 98: break;
          case 8: 
            { return symbol(Sym.DOT);
            }
          case 99: break;
          case 9: 
            { return symbol(Sym.IDENTIFIER, yytext());
            }
          case 100: break;
          case 10: 
            { return symbol(Sym.LPAREN);
            }
          case 101: break;
          case 11: 
            { return symbol(Sym.RPAREN);
            }
          case 102: break;
          case 12: 
            { return symbol(Sym.LBRACE);
            }
          case 103: break;
          case 13: 
            { return symbol(Sym.RBRACE);
            }
          case 104: break;
          case 14: 
            { return symbol(Sym.COMMA);
            }
          case 105: break;
          case 15: 
            { return symbol(Sym.EQ);
            }
          case 106: break;
          case 16: 
            { return symbol(Sym.PLUS);
            }
          case 107: break;
          case 17: 
            { return symbol(Sym.MINUS);
            }
          case 108: break;
          case 18: 
            { return symbol(Sym.GREATERTHAN);
            }
          case 109: break;
          case 19: 
            { return symbol(Sym.LESSTHAN);
            }
          case 110: break;
          case 20: 
            { yybegin(STRING); string.setLength(0);
            }
          case 111: break;
          case 21: 
            { string.append( yytext() );
            }
          case 112: break;
          case 22: 
            { throw new RuntimeException("Unterminated string at end of line");
            }
          case 113: break;
          case 23: 
            { yybegin(YYINITIAL); return symbol(Sym.STRING_LITERAL, string.toString());
            }
          case 114: break;
          case 24: 
            { return symbol(Sym.DIVEQ);
            }
          case 115: break;
          case 25: 
            { return symbol(Sym.MULTEQ);
            }
          case 116: break;
          case 26: 
            { return symbol(Sym.MODEQ);
            }
          case 117: break;
          case 27: 
            { return symbol(Sym.DECIMAL_LITERAL, new Double(yytext()));
            }
          case 118: break;
          case 28: 
            { return symbol(Sym.OF);
            }
          case 119: break;
          case 29: 
            { return symbol(Sym.AS);
            }
          case 120: break;
          case 30: 
            { return symbol(Sym.IF);
            }
          case 121: break;
          case 31: 
            { return symbol(Sym.IN);
            }
          case 122: break;
          case 32: 
            { return symbol(Sym.DO);
            }
          case 123: break;
          case 33: 
            { return symbol(Sym.TO);
            }
          case 124: break;
          case 34: 
            { return symbol(Sym.EQUALS);
            }
          case 125: break;
          case 35: 
            { return symbol(Sym.PLUSEQ);
            }
          case 126: break;
          case 36: 
            { return symbol(Sym.PLUSPLUS);
            }
          case 127: break;
          case 37: 
            { return symbol(Sym.MINUSEQ);
            }
          case 128: break;
          case 38: 
            { return symbol(Sym.MINUSMINUS);
            }
          case 129: break;
          case 39: 
            { return symbol(Sym.OR);
            }
          case 130: break;
          case 40: 
            { return symbol(Sym.GREATERTHANEQUALS);
            }
          case 131: break;
          case 41: 
            { return symbol(Sym.LESSTHANEQUALS);
            }
          case 132: break;
          case 42: 
            { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
            }
          case 133: break;
          case 43: 
            { string.append( '\\' );
            }
          case 134: break;
          case 44: 
            { string.append( '\n' );
            }
          case 135: break;
          case 45: 
            { string.append( '\f' );
            }
          case 136: break;
          case 46: 
            { string.append( '\r' );
            }
          case 137: break;
          case 47: 
            { string.append( '\t' );
            }
          case 138: break;
          case 48: 
            { string.append( '\"' );
            }
          case 139: break;
          case 49: 
            { string.append( '\b' );
            }
          case 140: break;
          case 50: 
            { string.append( '\'' );
            }
          case 141: break;
          case 51: 
            { return symbol(Sym.JAVASTRING, yytext());
            }
          case 142: break;
          case 52: 
            { return symbol(Sym.FOR);
            }
          case 143: break;
          case 53: 
            { return symbol(Sym.END);
            }
          case 144: break;
          case 54: 
            { return symbol(Sym.NOT);
            }
          case 145: break;
          case 55: 
            { return symbol(Sym.AND);
            }
          case 146: break;
          case 56: 
            { return symbol(Sym.BOOLEAN_LITERAL, true);
            }
          case 147: break;
          case 57: 
            { return symbol(Sym.ELSE);
            }
          case 148: break;
          case 58: 
            { return symbol(Sym.THEN);
            }
          case 149: break;
          case 59: 
            { return symbol(Sym.TYPE);
            }
          case 150: break;
          case 60: 
            { return symbol(Sym.STEP);
            }
          case 151: break;
          case 61: 
            { return symbol(Sym.LIST);
            }
          case 152: break;
          case 62: 
            { return symbol(Sym.NULL_LITERAL);
            }
          case 153: break;
          case 63: 
            { return symbol(Sym.CASE);
            }
          case 154: break;
          case 64: 
            { return symbol(Sym.VOID);
            }
          case 155: break;
          case 65: 
            { return symbol(Sym.BEGIN);
            }
          case 156: break;
          case 66: 
            { return symbol(Sym.BOOLEAN_LITERAL, false);
            }
          case 157: break;
          case 67: 
            { return symbol(Sym.WHILE);
            }
          case 158: break;
          case 68: 
            { return symbol(Sym.FORCE);
            }
          case 159: break;
          case 69: 
            { return symbol(Sym.COORD);
            }
          case 160: break;
          case 70: 
            { return symbol(Sym.GROUP);
            }
          case 161: break;
          case 71: 
            { return symbol(Sym.DOWNTO);
            }
          case 162: break;
          case 72: 
            { return symbol(Sym.STRING);
            }
          case 163: break;
          case 73: 
            { return symbol(Sym.SWITCH);
            }
          case 164: break;
          case 74: 
            { return symbol(Sym.RETURN);
            }
          case 165: break;
          case 75: 
            { return symbol(Sym.VECTOR);
            }
          case 166: break;
          case 76: 
            { return symbol(Sym.BOOLEAN);
            }
          case 167: break;
          case 77: 
            { return symbol(Sym.BARRIER);
            }
          case 168: break;
          case 78: 
            { return symbol(Sym.INTEGER);
            }
          case 169: break;
          case 79: 
            { return symbol(Sym.DEFAULT);
            }
          case 170: break;
          case 80: 
            { return symbol(Sym.DECLARE);
            }
          case 171: break;
          case 81: 
            { return symbol(Sym.DECIMAL);
            }
          case 172: break;
          case 82: 
            { return symbol(Sym.FOREACH);
            }
          case 173: break;
          case 83: 
            { return symbol(Sym.PLATOON);
            }
          case 174: break;
          case 84: 
            { return symbol(Sym.PROGRAM);
            }
          case 175: break;
          case 85: 
            { return symbol(Sym.TERRAIN);
            }
          case 176: break;
          case 86: 
            { return symbol(Sym.SOLDIER);
            }
          case 177: break;
          case 87: 
            { return symbol(Sym.FUNCTION);
            }
          case 178: break;
          case 88: 
            { return symbol(Sym.INTERRUPTS);
            }
          case 179: break;
          case 89: 
            { return symbol(Sym.SIMULATION);
            }
          case 180: break;
          case 90: 
            { return symbol(Sym.SIMULATIONS);
            }
          case 181: break;
          case 91: 
            { return symbol(Sym.DECLARATIONS);
            }
          case 182: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
