
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package com.company.SyntaxAnalysis;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int AS = 12;
  public static final int IDENTIFIER = 76;
  public static final int INTERRUPTS = 69;
  public static final int SOLDIER = 65;
  public static final int FORCE = 63;
  public static final int JAVASTRING = 77;
  public static final int GROUP = 61;
  public static final int GREATERTHANEQUALS = 51;
  public static final int BARRIER = 71;
  public static final int PLUSEQ = 41;
  public static final int COMMA = 30;
  public static final int SIMULATION = 67;
  public static final int RBRACE = 29;
  public static final int TERRAIN = 60;
  public static final int RPAREN = 27;
  public static final int SIMULATIONS = 66;
  public static final int INTEGER = 25;
  public static final int DECLARE = 15;
  public static final int LBRACE = 28;
  public static final int VECTOR = 70;
  public static final int LESSTHANEQUALS = 53;
  public static final int LPAREN = 26;
  public static final int INTEGER_LITERAL = 73;
  public static final int NOT = 48;
  public static final int COORD = 64;
  public static final int THEN = 57;
  public static final int EQ = 32;
  public static final int GREATERTHAN = 50;
  public static final int BOOLEAN_LITERAL = 72;
  public static final int MOD = 40;
  public static final int LESSTHAN = 52;
  public static final int PLUS = 35;
  public static final int WHILE = 4;
  public static final int DECIMAL = 13;
  public static final int BOOLEAN = 2;
  public static final int SWITCH = 21;
  public static final int DO = 5;
  public static final int FOR = 11;
  public static final int VOID = 58;
  public static final int DIV = 37;
  public static final int DOWNTO = 55;
  public static final int RETURN = 17;
  public static final int MULT = 39;
  public static final int ELSE = 18;
  public static final int DOT = 31;
  public static final int EOL = 54;
  public static final int NULL_LITERAL = 22;
  public static final int STRING_LITERAL = 75;
  public static final int EOF = 0;
  public static final int DEFAULT = 24;
  public static final int FUNCTION = 7;
  public static final int MULTEQ = 43;
  public static final int MINUS = 36;
  public static final int IN = 16;
  public static final int OR = 47;
  public static final int error = 1;
  public static final int DECIMAL_LITERAL = 74;
  public static final int DIVEQ = 44;
  public static final int LIST = 19;
  public static final int IF = 3;
  public static final int PLATOON = 62;
  public static final int MODEQ = 45;
  public static final int MINUSMINUS = 34;
  public static final int OF = 59;
  public static final int END = 8;
  public static final int FOREACH = 6;
  public static final int BEGIN = 9;
  public static final int CASE = 23;
  public static final int PLUSPLUS = 33;
  public static final int STRING = 14;
  public static final int STEP = 68;
  public static final int PROGRAM = 10;
  public static final int AND = 46;
  public static final int TO = 56;
  public static final int UMINUS = 38;
  public static final int DECLARATIONS = 20;
  public static final int EQUALS = 49;
  public static final int MINUSEQ = 42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "IF",
  "WHILE",
  "DO",
  "FOREACH",
  "FUNCTION",
  "END",
  "BEGIN",
  "PROGRAM",
  "FOR",
  "AS",
  "DECIMAL",
  "STRING",
  "DECLARE",
  "IN",
  "RETURN",
  "ELSE",
  "LIST",
  "DECLARATIONS",
  "SWITCH",
  "NULL_LITERAL",
  "CASE",
  "DEFAULT",
  "INTEGER",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "DOT",
  "EQ",
  "PLUSPLUS",
  "MINUSMINUS",
  "PLUS",
  "MINUS",
  "DIV",
  "UMINUS",
  "MULT",
  "MOD",
  "PLUSEQ",
  "MINUSEQ",
  "MULTEQ",
  "DIVEQ",
  "MODEQ",
  "AND",
  "OR",
  "NOT",
  "EQUALS",
  "GREATERTHAN",
  "GREATERTHANEQUALS",
  "LESSTHAN",
  "LESSTHANEQUALS",
  "EOL",
  "DOWNTO",
  "TO",
  "THEN",
  "VOID",
  "OF",
  "TERRAIN",
  "GROUP",
  "PLATOON",
  "FORCE",
  "COORD",
  "SOLDIER",
  "SIMULATIONS",
  "SIMULATION",
  "STEP",
  "INTERRUPTS",
  "VECTOR",
  "BARRIER",
  "BOOLEAN_LITERAL",
  "INTEGER_LITERAL",
  "DECIMAL_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER",
  "JAVASTRING"
  };
}

