Begin Declarations
  Declare terrain as Terrain
End Declarations

Declare Simulations

End Declare Simulations

Type Coord
  Declare X as Decimal
  Declare Y as Decimal

  Function String ToString()
    Return "(" + X + "," + Y + ")"
  End Function
End Type

Type Vector
  Declare X as Decimal
  Declare Y as Decimal

  Function String ToString()
    Return "(" + X + "," + Y + ")"
  End Function

  Function Decimal GetLength()
    Declare res as Decimal
    %`` res = Math.abs(Math.sqrt( Math.pow(X, 2) + Math.pow(Y , 2)));
    Return res
  End Function
End Type

Type Terrain
  Declare Width as Integer
  Declare Height as Integer

  Function Void Hej()
  End Function
End Type

/*Type DSTFunctions
  Declare Hej as Integer
  Function Vector FindUnitVector(startCoord as Coord, targetCoord as Coord)
    Declare res as Vector
    res.X = targetCoord.X - startCoord.X
    res.Y = targetCoord.Y - startCoord.Y
    Declare length as Decimal
    length = res.GetLength()
    res.X /= length
    res.Y /= length
    Return res
  End Function
End Type
*/
Type Soldier
  Declare DefaultVelocity as Decimal
  Declare Size as Integer
  Declare Velocity as Decimal
  Declare Magazines as Integer
  Declare Pos as Coord
  Declare Direction as Vector

  Function Void Soldier()
    DefaultVelocity = 3 //Change this because this is a random number
    Size = 4            //Change this because this is a random number
    Velocity = 0
    Magazines = 4
  End Function

  Function Void Move(target as Coord)
    If Velocity == 0 Then
      Velocity = DefaultVelocity
    End If
    Declare res as Vector
    res.X = target.X - Pos.X
    res.Y = target.Y - Pos.Y
    Declare length as Decimal
    length = res.GetLength()
    res.X /= length
    res.Y /= length
    Return res
  End Function



End Type

Function Void Hej()
End Function

#Include("stdlib.bsi")

Begin Program
  terrain.Width = 2000
  terrain.Height = 2000

  Declare Base as Coord
  Base.X = 5
  Base.Y = 17

  Declare Vec as Vector
  Vec.X = 3
  Vec.Y = 4

  Declare Vec2 as Vector
  Vec2.X = 3.4
  Vec2.Y = 10.7

  PrintLine("Vec.GetLength: " + Vec.GetLength())
  PrintLine("")
  PrintLine("Base.ToString" + Base.ToString())
  PrintLine("Vec.ToString" + Vec.ToString())
End Program
